### ISSUE TITLE
Not tracking the project when I use SSH and coding in Rust

### ISSUE THREAD

**Issue by w93163red** [swdotcom/swdc-vscode#107]
**Describe the bug**
When I use SSH to remote develop a rust project, the time is not updating.

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Use SSH to remote login a PC
2. Open a rust project
3. Random type something

**Expected behavior**
the time and keystroke should be recorded.

**ACTUAL RESULTS**
The data is not updating.
![image](https://user-images.githubusercontent.com/7308728/86868571-fbcd6b80-c0a2-11ea-9871-712471fbce6e.png)
Compare to wakatimes:
![image](https://user-images.githubusercontent.com/7308728/86868603-0a1b8780-c0a3-11ea-98a9-6dcc1763e22e.png)

The time is not matching. Wakatimes shows the exact time I worked on VSCode. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin version Code Time 2.2.27

**Comment by mmclead** [comment]
Hi @w93163red, we've made huge updates to our data tracking since July.   Is this still an issue for you?
