### ISSUE TITLE
Not calculate time in vscode with openSUSE linux

### ISSUE THREAD

**Issue by sakanamax** [swdotcom/swdc-vscode#11]
Code Time work good with my Mac.
But not calculate time with openSUSE Linux.

OS: openSUSE Leap 15
VScode: 1.31.1
code time: 0.6.9

I already try restart vscode and re-install code time, but still not work at openSUSE Linux.

Any thing I could do?
Thanks.

**Comment by andrewhli** [comment]
HI Max. Thanks for trying the extension on Mac and apologies for wasting your time on Linux. We're still testing and bug fixing for Linux, so your note will help us in the coming week.

**Comment by sakanamax** [comment]
Thanks @andrewhli 
I think code time is cool and I suggest this extension to my community.
Wait for your good news :)

**Comment by andrewhli** [comment]
Hi @sakanamax - we're live on Product Hunt! Would appreciate any support you can give: https://www.producthunt.com/posts/code-time. We're looking to support Linux post-launch

**Comment by brettmstevens7** [comment]
Hi @sakanamax - can you test that you are now able to log in to your account on Linux?

**Comment by sakanamax** [comment]
@brettmstevens7 Cool, I could login to my account and see code time in Linux.
OS: openSUSE Leap 15
VScode: 1.32.3
code time: 0.11.9
