### ISSUE TITLE
Code Time context menus seem to be added to every tree view

### ISSUE THREAD

**Issue by lostintangent** [swdotcom/swdc-vscode#12]
I just noticed that when I right-click in any custom tree view in VS Code (e.g. the Live Share session details tree), the Code Time context menus appear (see below for the experience with the Live Share tree). It would be great if you could scope these commands to a specific context, so it doesn't clutter any UI unexpectedly.

<img src="https://user-images.githubusercontent.com/116461/53290876-4c1e8480-375f-11e9-87cf-81536414c57d.png" width="300px" />

**Comment by andrewhli** [comment]
Thanks, Jonathan. This is very good to know. We'll fix it this weekend. Let us know if you see any other improvements.
