### ISSUE TITLE
Negative code time

### ISSUE THREAD

**Issue by LeedanJohnson** [swdotcom/swdc-vscode#14]
Today I was seeing negative values (~-200 min) in the Total for the day. I'm not sure how far that negative value had propagated.
(Note. I just want to mention that I'm opening another issue for the extension crashing Visual Studio 2017. I don't know if there's any chance they'd be related)

**Comment by andrewhli** [comment]
Hi there. Appreciate your note and apologies for wasting your time. This bug was related to the high traffic issue we've been experiencing. The traffic and scaling issues have been resolved, so please let us know if this continues to be an issue.

**Comment by andrewhli** [comment]
Hey there. The database upgrade is done, and the app loads much faster now. Please let me know if you see any other problems.
