### ISSUE TITLE
tracking the same project on different devices

### ISSUE THREAD

**Issue by TahseenAlaa** [swdotcom/swdc-vscode#155]
**Describe the bug**
```paste below
Hi, I'm using this extension a few days ago and It's great, now I'm using two computers for working on the same project and I noticed that the extension didn't sum the time spend on the two computers even when I sync the project repo, also both computers have the same OS (Windows 10 x64) and the same VS code version and the same Code time version.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Plugin version: 2.3.12

**Additional context**
```paste below

```

**Comment by mmclead** [comment]
Hi @TahseenAlaa.   We've updated a lot of our data tracking in the past months and, this should be resolved if you are logged in on both machines and pull reports.   

Please let me know if that's not the case.
