### ISSUE TITLE
Extension host crash when using codetime in remote ssh mode

### ISSUE THREAD

**Issue by EthanZeigler** [swdotcom/swdc-vscode#158]
**Desc:**
Extension host crashes when using codetime in remote ssh mode

**Steps to reproduce:**
- use remote ssh from microsoft (ms-vscode-remote.remote-ssh-edit)
- have codetime enabled
- wait for extension host to crash (usually < 2 min)

**Console backtrace:**
```
console.ts:137 [Extension Host] swdc-tracker initialized and ready to send events to com-software-prod1.collector.snplow.net
console.ts:137 [Extension Host] swdc-vscode: storing kpm metrics
bootstrap-window.js:216 [uncaught exception]: Error: read ECONNRESET
bootstrap-window.js:219 Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200)
events.js:200 Uncaught Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200)
bootstrap-window.js:216 [uncaught exception]: Error: read ECONNRESET
bootstrap-window.js:219 Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200)
events.js:200 Uncaught Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200)
```

**Comment by meskill** [comment]
Same issue while using remote container extension

**Comment by PCPbiscuit** [comment]
I have the same exact issue

**Comment by Niaro** [comment]
Same here, can't use this awesome extension in remote SSH mode(

**Comment by mmclead** [comment]
Hi there.  We'll start taking a look at this one.   It's an interesting use case here.  Seems like it's currently incompatible with the metric tracking.

**Comment by xavluiz** [comment]
Hi,
Based on the latest version, 2.5.23, this doesn't seem to have any issues around remote ssh mode. I've tested this use case on MacOS using Remote - SSH 0.65.7 and our plugin 2.5.23. Would anyone else here be able to verify if this is still an issue with the latest Code Time version? We've had a number of updates in regards to fixing performance and general telemetry optimizations. Thanks.

**Comment by PCPbiscuit** [comment]
I can confirm that everything works fine in ssh

**Comment by meskill** [comment]
Seems good so far with remote container
