### ISSUE TITLE
Coding time vs 'break/stand-up' time

### ISSUE THREAD

**Issue by EnergeticPixels** [swdotcom/swdc-vscode#159]
##### SUMMARY

```paste below
I can code for hours on end.  I have both this extension and Take-a-Break extension loaded.  Take a Break is used to remind me there is an outside world and that I should change my eye focus and stand-up every now and then.  During COVID situation I find myself coding for longer and longer periods.
```

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

```paste below
If I get distracted during a break, (happens often at the office), it would be nice that the feature would suspend time tracking.  I would also be helpful if there was a timer inside (programmer controlled) that would tell us to stand up every now and then.
```

**Comment by mmclead** [comment]
Hi @EnergeticPixels.  Thanks for the feedback.    For the suspension of time tracking, we do have coding sessions time out after a period of inactivity.   The full definition is here: https://docs.software.com/article/27-what-is-code-time.  

Also, I like your suggestion for the timer to remind people to stand up and enjoy the outside world every now and again too.   We do show some stats around work / life balance with our hours spent during and outside of work hours.  

I personally believe that we, as developers, don't necessarily need to spend more time developing, we need more focused time.   And that is a goal we are building some super interesting tools for that will coming in the next couple months.

Thanks for using our products and for the suggestions.   Let me know if there is anything else I can help with.

**Comment by mmclead** [comment]
I'm going to close this issue as we have this suggestion on our internal lists now. 

Thanks again!
