### ISSUE TITLE
Not able to access app.software.com/dashboard

### ISSUE THREAD

**Issue by Joel-hanson** [swdotcom/swdc-vscode#165]
**Describe the bug**
```paste below
I am not able to access the app.software.com. I am getting a blank white screen after a glance of the dashboard is shown.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Go to 'software.com'
2. Click on 'login'
3. login using Github

**Expected behavior**
```paste below
The page should load without any issue.
```

**ACTUAL RESULTS**

These are the steps which I had followed.
```paste below
1. Go to 'software.com'
2. Click on 'login'
3. login using Github
4. See error

```

**Screenshots**
<img width="522" alt="Screenshot 2020-10-31 at 10 22 06 AM" src="https://user-images.githubusercontent.com/17215044/97771507-87439e80-1b63-11eb-81b9-fbc8be687650.png">
<img width="1318" alt="Screenshot 2020-10-31 at 10 28 10 AM" src="https://user-images.githubusercontent.com/17215044/97771542-cb36a380-1b63-11eb-97e4-24fcacb5a6d9.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrome Version 86.0.4240.111 (Official Build) (x86_64)
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by xavluiz** [comment]
Thank you for the issue update and we apologize for the inconvenience. We encountered a connection issue that is now resolved.
Regards.

**Comment by Joel-hanson** [comment]
It's resolved now. Thanks @xavluiz
