### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Kirun1** [swdotcom/swdc-vscode#170]
- Issue Type: `Performance`
- Extension Name: `swdc-vscode`
- Extension Version: `2.3.18`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ps\AppData\Local\Temp\softwaredotcom.swdc-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mmclead** [comment]
We've made significant updates to address this.   Closing for now.  Please let us know if you see anything else.
