### ISSUE TITLE
cant login on Linux

### ISSUE THREAD

**Issue by bigpodgurc** [swdotcom/swdc-vscode#19]
Cant login on linux with all programs i use
(vscode atom idea pycharm) it pushes me to the page and i login and thats it

**Comment by andrewhli** [comment]
Thanks for letting us know! Right now, we don't 100% support Linux. We're looking to add support later in the month, and I'll be sure to let you know.

**Comment by bigpodgurc** [comment]
Well if i understand correctly it should work since it is an extension
problem is that u guys use browser to log in if you used the program
extension is in it would work 100% my guess is during the connection
between browser and program there is some problem. You guys are with the
non support for linux also missing great part of your audience.

**Comment by andrewhli** [comment]
You're correct that it's an extension problem and that we're missing a great part of the audience. We just need time to test and fix on Linux. Going to get Linux set up this week so we can fix these. Thanks for diagnosing that the problem could be during the connection. We'll look into that first. Let me know if you have any other ideas on what might be wrong.

**Comment by MartinJesus23** [comment]
![image](https://user-images.githubusercontent.com/26811053/54302357-fd774400-45c0-11e9-9948-03f9f56e2d8c.png)

-Same problem in linux, hope u can fix it soon.

**Comment by m6devin** [comment]
+1
I can log in from mac but I can't log in from Linux(Debian + gnome)

**Comment by MartinJesus23** [comment]
Last update Working in vscode (arch linux) thank you.
![image](https://user-images.githubusercontent.com/26811053/54462317-9d72d000-476f-11e9-8517-b95b2d625009.png)
![image](https://user-images.githubusercontent.com/26811053/54462331-a9f72880-476f-11e9-91b6-b78258bd084c.png)

**Comment by brettmstevens7** [comment]
@m6devin We updated all of our plugins to now use a hashed unique user ID instead of a MAC address for authentication. Can you test if you are able to log in now on Linux?

**Comment by m6devin** [comment]
Of course, I'll test it today!

**Comment by m6devin** [comment]
I was able to login.

**Comment by brettmstevens7** [comment]
Thanks @m6devin - we're working now on the other data issue you were seeing last week. 

@bigpodgurc you should now be able to log in on Linux with the latest plugin version - let me know if you have any trouble.
