### ISSUE TITLE
Software.com-related commands appear in context menus of unrelated explorer panes

### ISSUE THREAD

**Issue by ewired** [swdotcom/swdc-vscode#2]
As much as I would like to order tacos, I'm questioning the involvement of PowerShell, VS Live Share or GitLens in that activity:
![image](https://user-images.githubusercontent.com/37567272/50547862-5f521f80-0c08-11e9-811c-777af3b95e64.png)
![image](https://user-images.githubusercontent.com/37567272/50547868-785ad080-0c08-11e9-93d6-01eb3c5a9de7.png)
![image](https://user-images.githubusercontent.com/37567272/50547890-d4bdf000-0c08-11e9-9336-770a3513d655.png)

**Comment by brettmstevens7** [comment]
Hey @ewired we've removed this feature from the commands.

**Comment by andrewhli** [comment]
Hi @ewired - we're live on Product Hunt! Would appreciate any support you can give: https://www.producthunt.com/posts/code-time
