### ISSUE TITLE
Not work in mac

### ISSUE THREAD

**Issue by nicobytes** [swdotcom/swdc-vscode#20]
I have this plugin but 1 week ago not work 

![Screen Shot 2019-03-12 at 6 36 06 PM](https://user-images.githubusercontent.com/7611944/54243253-ba03d380-44f5-11e9-9d48-01bae883fafa.png)

Code time show nothing

I have Vscode 1.32.1

**Comment by wickeym** [comment]
Hi,

It seems to be quite buggy still for me too.
If you close vscode, delete ~/.software/.session.json then re-open and re-login into code time it seems to work again, at least for a while.

Sincerely,
Michael

**Comment by OsirisFrik** [comment]
> Hi,
> 
> It seems to be quite buggy still for me too.
> If you close vscode, delete ~/.software/.session.json then re-open and re-login into code time it seems to work again, at least for a while.
> 
> Sincerely,
> Michael

This work for my, but maybe add a load card to get a UX of quip process the login response and don't try again.
