### ISSUE TITLE
Code Time Data for the Project Name and File Type

### ISSUE THREAD

**Issue by Astrantia** [swdotcom/swdc-vscode#21]
It's sometimes interesting to see how much time we spend on a particular project. The project's name can be inferred from the Folder name.
The other feature request is about File Types, because we want to know how much time we spend coding in some language.

**Comment by Astrantia** [comment]
@xavluiz is this possible?

**Comment by xavluiz** [comment]
We do provide a "top projects" weekly chart based on file path and project name. We are still working out the details when a file is not yet associated to a project but any feedback and ideas are welcome. We also provide the ability to assign a currency rate to show how much one would charge for the time spent on a specific project. Let me know if you have any other questions or ways of displaying project analytics that can better help your daily productivity. Thank you again.

Xavier

**Comment by afliw** [comment]
I don't see any of those options in my dashboard (not projects nor languages):

![image](https://user-images.githubusercontent.com/6609070/56574107-5cfe4180-65ba-11e9-9d9a-c055b75b786f.png)

**Comment by gsabater** [comment]
Still nothing about this?
I think that knowing the amount of time spent on each project is the most important metric for a lot of people who work by hours, and also, it's the most important featured that offers some other time trackers.

**Comment by andrewhli** [comment]
Hi Gaspar. We've received a lot of feedback about this feature and are working on it. It required a DB schema change, and so it's taking some time to ensure it integrates well with current features.
