### ISSUE TITLE
Dashboard shows wrong code time

### ISSUE THREAD

**Issue by m6devin** [swdotcom/swdc-vscode#22]
I'm using Code Time in VsCode on mac.
It is showing the wrong time: look at this report:
```
CODE TIME          (Last updated on Fri, Mar 15th 8:10 am)

Today (Fri, Mar 15th)
-----------------------------------------------------------------
        Hours coded today: 4.9 hrs
               90-day avg :                                0 min
               Live Share :                                0 min

Yesterday (Thu, Mar 14th)
-----------------------------------------------------------------
              Hours coded :                                    0
      Lines of code added :                                    0
    Lines of code deleted :                                    0
         Characters added :                                    0
       Characters deleted :                                    0
         Total keystrokes :                                    0
                      KPM :                                    0
               Live share :                                0 min
```
It shows that I spent about 5 hours to code on Friday! Actually, it is for Thursday(yesterday).
Yesterday, every time I checked, It showed 0 min of code! But today it is showing that I coded 5 hours and actually I was at sleep! and it is the exact time of code for yesterday.

Here is also a screenshot of my online dashboard:
<img width="369" alt="Screen Shot 1397-12-24 at 08 15 48" src="https://user-images.githubusercontent.com/13257674/54409176-a70e2080-46fa-11e9-9b16-aa15956ea7bf.png">

**Comment by prydda** [comment]
I'm having the same issue. 
It's like code time is delayed with 24 hours, 
When my local time hit 00.00 Code time showed I've been coding 5 hours. 

I've deleted the hidden folder /.software under Users/myUsername. Logged in on the website once more and still showing delayed code info. 

And one more thing. It's not updating in realtime anymore, I'm only getting new stats at midnight, both in editor and on the webpage.

**Comment by m6devin** [comment]
I'm chacking it from morning till now, here is my new report:
```
CODE TIME          (Last updated on Fri, Mar 15th 5:41 pm)

Today (Fri, Mar 15th)
-----------------------------------------------------------------
        Hours coded today: 4.9 hrs
               90-day avg :                                0 min
               Live Share :                                0 min
```

You can see it's updated at 5:41 PM but I'm coding from morning till now and it's not logged!

**Comment by volkoff-pro** [comment]
Same issue too.
I'm using VS Code v1.32.3, Code Time extension v0.11.2
Looks like stats shown for data about couple day ago and not updated properly.

**Comment by andrewhli** [comment]
Hi everyone. Thanks for letting us know about this issue. After some debugging, It looks like a moment.js function we're using is ignoring user timezones for users with +UTC offsets. Testing it here in San Francisco, we didn't see this issue earlier. We've been working to fix it and will give everyone an update after the weekend. @m6devin @prydda @volkoff-pro
