### ISSUE TITLE
Logging in with an email doesn't work

### ISSUE THREAD

**Issue by borisvu** [swdotcom/swdc-vscode#220]
**Describe the bug**
```paste below
Logging in via email doesn't work.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Click on "Log in" in VSCode extension.
2. Choose ""Log in via email"
3. Browser window opens
4. Provide email and password.
5. Click on "log in"

**Expected behavior**
```paste below
User logged in both browser and VSCode extension.
```

**ACTUAL RESULTS**

```paste below
User logged in the browser but not VSCode extension.
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Plugin version 2.4.0
 - Browser Firefox 84.0.2

**Comment by brettmstevens7** [comment]
Thanks, we'll get this fixed.

**Comment by borisvu** [comment]
Fixed in the latest update, thanks!
