### ISSUE TITLE
Overly broad permissions for Calendar integration

### ISSUE THREAD

**Issue by thecontstruct** [swdotcom/swdc-vscode#228]
**Describe the bug**

When connecting a google calendar, the permission it requests seem overly broad. Why does your service need the ability to edit/delete/create events/entire calendars? It's kind of paranoia inducing, especially when you're dealing with your corporate calendar and potentially sensitive information there in.

**ISSUE TYPE**
- Permissions Issue

**Steps to reproduce**

1. Connect a google calendar to your account

**Expected behavior**

Maybe there are other reasons involved but from the description of the feature, it sounds like you'd only need read access to the calendar. Even then, if all you need is timing information, then you also wouldn't need who all attended or the name of the events since those can expose sensitive information.

**ACTUAL RESULTS**

Requests total access to the calendar including the ability to delete everything

**Screenshots**
![Screen Shot 2021-01-29 at 8 52 52 AM](https://user-images.githubusercontent.com/4115757/106283162-904e1580-620f-11eb-964c-8a087c6616b9.png)

**Additional Comments**
Just wanted to add that I really like the insights this software provides me and really want to use the calendar feature since I'd love to get more insights into what meetings are sucking up my time. As it stands though I don't feel I can risk it :(

**Comment by mmclead** [comment]
Looking into this now.  Thanks

**Comment by mmclead** [comment]
I've opened a PR to fix this issue.  It should be available in production within a day to two.

The new reduced scopes will show this:

![Screen Shot 2021-02-09 at 11 20 25 PM](https://user-images.githubusercontent.com/898851/107482467-9360d400-6b34-11eb-8c7e-c7b61b19a0b7.png)

**Comment by mmclead** [comment]
This is live now!   

Thanks for bringing this up to us.    Closing the ticket.  But please reopen if you need to.

**Comment by thecontstruct** [comment]
Fantastic! Thanks for the quick turn around!
