### ISSUE TITLE
How can I sign out?

### ISSUE THREAD

**Issue by xiaonuo915** [swdotcom/swdc-vscode#23]
Dear:
I want change my account, But there seems to be no logout option in the extension.
or
Is there any way to change my account login?

Thanks.
Have a good time.

**Comment by brettmstevens7** [comment]
Hi @xiaonuo915 - to switch accounts, you can delete the `.software` folder in your home directory (a new folder will automatically appear after a few seconds). This will effectively log you out on your device and create a new plugin account. After you delete this folder, you can click the status bar to open up the command menu and log in to a new account.
