### ISSUE TITLE
Code Time Not showing any result on my VS-Code

### ISSUE THREAD

**Issue by utkarshg6** [swdotcom/swdc-vscode#230]
**Code Time is not showing any information**
I have tried reinstalling the plugin. It used to work in past but not anymore. I am running it on Windows. I have Music Time installed too and it works perfectly.

**ISSUE TYPE**
- Bug Report

**Expected behavior**
Since on the browser, my account is connected. It should reflect all the code updates. It used to work in past and I am able to see old stats on the browser from the time when it used to work.

**ACTUAL RESULTS**
No Updates are reflected.

**Screenshots**
![bug-code-time](https://user-images.githubusercontent.com/32920299/106383344-5cc7e280-63eb-11eb-8887-cb760dda82d6.JPG)

**Desktop Configuration**
 - OS: Windows 10
 - Plugin version: Code Time v2.4.5

**Comment by xavluiz** [comment]
Thank you for the issue update and we apologize for any inconvenience. We'll look into this right away. Are there any errors in Developer Tools window? You can find these by selecting: Help -> Toggle Developer Tools. 

I currently have both music time and code time installed on a windows 10 device but we'll investigate this today.
Regards.

**Comment by utkarshg6** [comment]
@xavluiz My console is showing two errors but I think they're unrelated to Code Time. One is due to `tabnine` and the other is due to `DeprecationWarning: Buffer()`.

**Comment by xavluiz** [comment]
Can you try deleting your <home>/.software directory and reloading vscode? Do you have code time running on any other IDE's besides vscode, like visual studio? Once you delete your software directory and reload, the tree view should display the account items and you should be able to see the log in and sign up button.  I'm still looking into why the tree view items are not getting displayed in the meantime.

**Comment by utkarshg6** [comment]
I did that. Though Music Time asked me to connect to Spotify but Code Time remains the same.

**Comment by xavluiz** [comment]
We're still looking into this and will confirm with the team tomorrow about reproducing the issue. What is the your VSCode version?
Thanks.

**Comment by utkarshg6** [comment]
Here are the version details.

```bash
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

I am using the [SynthWave '84 Theme](https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode) which makes the `vs-code` to be always opened in the unsupported mode.

![vs-code unsupported](https://user-images.githubusercontent.com/32920299/106428339-cfd66500-648e-11eb-8dde-e198660dea90.JPG)

The confusing part is that this **unsupported mode** runs _Music Time_ with perfection but fails in the case of _Code Time_.

**Comment by xavluiz** [comment]
Thank you for the information. We're currently testing against 1.52.1 on windows. Would you be able to try debugging the plugin? This would allow us to understand if it may be related to the following issue that seems similar: https://github.com/microsoft/vscode/issues/79371

**Comment by mmclead** [comment]
Do you still have this issue?  The latest version has an entirely rebuilt UI.

**Comment by utkarshg6** [comment]
Yes, I still have this issue. I reinstalled the plugin but it is still not showing me any stats.
