### ISSUE TITLE
Where did the daily report go inside the IDE after the updates?

### ISSUE THREAD

**Issue by mrakcw** [swdotcom/swdc-vscode#231]
**Describe the bug**
```paste below
Explain to me, please, where did the daily report go inside the IDE after the updates?
```
**ISSUE TYPE**
- Couldn't find daily work time report
- Below is a screenshot for 11/06/2020 as an example of a daily statistics report

**Screenshots**
https://mrakcw.github.io/cdn/img/codetime.jpg

**Desktop (please complete the following information):**
 - OS: [Windows 10 20H2 (19042.746)]
 - Plugin version [e.g. Code Time v2.4.5]

**Additional **
```
maybe I'm looking in the wrong place, but I searched for about 30 minutes and found nothing.
```

**Comment by brettmstevens7** [comment]
@mrakcw cool, thanks for opening up this issue. What do you like about that dashboard? What metrics are missing in the new one that you'd like to see?

**Comment by mrakcw** [comment]
> @mrakcw cool, thanks for opening up this issue. What do you like about that dashboard? What metrics are missing in the new one that you'd like to see?

nothing specific, just the summary information for the day in a text document interests.  it was previously available in the third or fourth item on the top sidebar. But  now it is not there and in the settings I did not find it either.  the site displays general information without specifics as in this document

**Comment by mmclead** [comment]
The link to the Dashboard has been moved to a lower spot than before:
![Screen Shot 2021-02-01 at 9 44 50 AM](https://user-images.githubusercontent.com/898851/106497155-8d069400-6472-11eb-90bd-425a464bbbbc.png)

We'll also be making improvements to it so it will look like this:
![106342293-2c4e4000-6255-11eb-9a25-a1e08589aa3e](https://user-images.githubusercontent.com/898851/106507483-f8a32e00-647f-11eb-8f5b-092fdef74917.png)

**Comment by mmclead** [comment]
@mrakcw did that answer your question?

Were you able to find the dashboard now?

**Comment by mmclead** [comment]
How about something like this above the charts:

![Screen Shot 2021-02-02 at 2 38 45 PM](https://user-images.githubusercontent.com/898851/106672143-72144c80-6564-11eb-9840-3ec51775f8fb.png)

**Comment by mmclead** [comment]
I'm glad you are enjoying it!

BTW, have you checked out Flow Mode yet?    It's my new favorite button in VS Code, by far.

**Comment by mrakcw** [comment]
@mmclead no, I haven't researched this item and the service yet)) I will definitely read it

**Comment by mmclead** [comment]
![Flow Mode](https://user-images.githubusercontent.com/898851/106674956-0385bd80-6569-11eb-9b24-3713cac2739e.png)

Flow Mode is part of CodeTime. 

Connect Slack and it will automatically mute notifications and set your status.
We'll be building Calendar integrations soon too.

And, pretty soon it will be able to detect when you are getting into "flow" and automatically enable the feature to protect your time.

**Comment by mrakcw** [comment]
> ![Flow Mode](https://user-images.githubusercontent.com/898851/106674956-0385bd80-6569-11eb-9b24-3713cac2739e.png)
> 
> Flow Mode is part of CodeTime. 
> 
> Connect Slack and it will automatically mute notifications and set your status.
> We'll be building Calendar integrations soon too.
> 
> And, pretty soon it will be able to detect when you are getting into "flow" and automatically enable the feature to protect your time.
> 
> 
> 
> 

Very nice 👍

**Comment by mmclead** [comment]
The latest version of the dashboard is live now.
![Screen Shot 2021-02-09 at 10 46 53 AM](https://user-images.githubusercontent.com/898851/107412095-2150a680-6ac4-11eb-99df-9d6e50b7a72f.png)


Closing the issue since, I believe, your question is answered.
