### ISSUE TITLE
Feature Request: Status Bar Toggles

### ISSUE THREAD

**Issue by mpearon** [swdotcom/swdc-vscode#24]
This might be trivial, but I think that the ability to remove Status Bar Items would be nice - or possibly provide the option to show an icon instead?

As you can see in the following image, my status bar gets pretty full - and CodeTime is a big offender.  The notification on the left side doesn't show up all the time, but when it does, it appear to only be notifying that I've hovered an option in the Command Palette.

![Status Bar](https://user-images.githubusercontent.com/7157790/54608057-ebacfb00-4a1d-11e9-9058-178b7bb33804.png)

**Comment by brettmstevens7** [comment]
@mpearon - I think you've probably seen it already, but we added a show/hide status toggle to the command menu per your feedback. Thanks!

**Comment by mpearon** [comment]
Thanks, @brettmstevens7! I do have a suggestion, though: I think that option should be moved to the Settings JSON/UI.

A lot of people use extensions like [Syncing](https://github.com/nonoroazoro/vscode-syncing) and [Settings Sync](https://github.com/shanalikhan/code-settings-sync) to keep vsCode instances in sync.  Including these options in the JSON or UI would keep them from having to change this on all their machines.

Possibly trivial, but definitely something I'm effected by.
