### ISSUE TITLE
Toggle Zen Mode is not easy to toggle

### ISSUE THREAD

**Issue by twocs** [swdotcom/swdc-vscode#241]
**Expected behavior**
I clicked Zen Mode. It made everything full screen. Then I wanted to toggle it off. But there is no button to do that?!??!

**ACTUAL RESULTS**
Ok, cool, I see what Zen Mode is now, but now I want to stop it. I want to see the sidebar. Where is it? How do I stop this Zen Mode? 

Luckily I figure it out that I can do Ctrl Shift P and search for Zen mode and then toggle it that way, but what about a newer VS Code user?  You need to make it easier to leave this mode! If that mode hides many main functions of the IDE, then the deactivation button must be prominent, never hidden, and described when they first click Zen Mode.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin version [e.g. Code Time v2.4.7]

**Comment by mmclead** [comment]
We added a shortcut to VS Code's built in Zen Mode.   To exit, push esc twice. 

https://code.visualstudio.com/docs/getstarted/tips-and-tricks

But, we are removing it in an upcoming version.  I haven't heard of anyone who actually likes Zen mode.
