### ISSUE TITLE
Is there something wrong with the statistics?

### ISSUE THREAD

**Issue by eyelly-wu** [swdotcom/swdc-vscode#243]
Check the dashboad in vscode, as shown in the figure below. The time below should be shorter than that above
![image](https://user-images.githubusercontent.com/24505069/107331256-971d3800-6aed-11eb-85d5-3e02d2dc30a1.png)

**Comment by mmclead** [comment]
Hi @eyelly-wu.  Thanks for pointing that out.    Based on our definitions of each of those measures, Time in Editor should always be more than Active Code Time.   We are looking into what could have caused that now.

**Comment by bjacobson26** [comment]
hi @eyelly-wu - thank you for opening up this issue. We deployed a fix. Going to close this, but feel free to open it back up if you continue to have issues. 

Thank you! ✌️
