### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by 0x000613** [swdotcom/swdc-vscode#246]
**Describe the bug**
The plug-in terminates with the error "Extension host terminated unexpected".

We thought it might be a conflict issue with other plug-ins, so we shut down all other plug-ins and ran Code Time only, but the results are still the same.
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Big sur
 - Plugin version 2.4.9

**Additional context**
```paste below

```

**Comment by bastienboutonnet** [comment]
I've also been experiencing this bug on a Big Sur M1 mac. It took me a while to realise which extension was causing the issue but when looking at the logs, I saw that errors bubbled up from this extension.

I turned it off but I'd be happen to turn it back on and provide some logs if this would be helpful here.

**Comment by askdesigners** [comment]
Ya logs could definitely be helpful. I've seen that error a few times too, but it's sporadic and I haven't been able to reliably recreate it. I got a new machine recently and that error hasn't happened at all, so maybe it's a conflict with some other extension?

**Comment by xavluiz** [comment]
Hi,
We've fixed a number of performance and add telemetry optimizations over the versions and would love to hear if this is still an issue with any of you with v2.5.23. Thank you.
