### ISSUE TITLE
Non-Login usage silently broken since v2.5

### ISSUE THREAD

**Issue by 0xpr03** [swdotcom/swdc-vscode#258]
**Describe the bug**
```paste below
SInce the 2.5 update I don't get any more stats without creating some kind of account and all my stats are gone ?!
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Upgrade from 2.4 to 2.5

**Expected behavior**
```paste below
Offline usage without account, no statistics lost.
```

**ACTUAL RESULTS**

```paste below
Everything is gone and the plugin is useless.
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below
I don't see why this requires external accounts. Its even kinda illegal for me to make my personal worktime completely trackable on external services.
```

**Comment by mmclead** [comment]
If collecting data about your work is not allowed for your employer, then version 2.4 has the same issue as version 2.5.  It was always collected and aggregated in a data process flow that is not on your machine.   All our code concerning this is open source and we take great lengths to protect and hide your sensitive data from our systems and any others.   You can read more here about our approaches:  https://www.software.com/data-privacy

We set up the extension to have a login process to enable a weekly summary email and give access to the web based dashboards that have a lot of additional features.   

Your data is still there before you create the account, its just not associated with your login yet.   You can connect via Github, Google, or setup an email/password account and get access to all of that for free, plus new features like Flow Mode and suggestions to protect Code Time on your calendar.
