### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by iaxat** [swdotcom/swdc-vscode#260]
- Issue Type: `Performance`
- Extension Name: `swdc-vscode`
- Extension Version: `2.5.7`
- OS Version: `Darwin x64 20.3.0`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/ll/8cz3qxzn5bl47ngvx44ydx9c0000gn/T/softwaredotcom.swdc-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mmclead** [comment]
Thank you for reporting.  We will look into this.

**Comment by xavluiz** [comment]
Hi @iaxat , would you be able to provide the cpuprofile report in a way we can download it? It doesn't appear to be available in the issue report, thank you.

**Comment by iaxat** [comment]
I tried to find it but I am not able to. I will try to see if I can find it and will post it as soon as I can.

**Comment by avkulikov** [comment]
Hello. 
[softwaredotcom.swdc-vscode-unresponsive.cpuprofile.txt](https://github.com/swdotcom/swdc-vscode/files/6828865/softwaredotcom.swdc-vscode-unresponsive.cpuprofile.txt)
 I am experiencing similar problems
Версия: 1.59.0-insider
Фиксация: 50b3811fdc5b5c80ca516a2edfffedcbd464b033
Дата: 2021-07-15T05:13:18.937Z
Electron: 13.1.6
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
ОС: Linux x64 5.11.0-24-lowlatency

**Comment by iaxat** [comment]
Yes it does, but in the new version of VS Code it seems to work fine without any issues, although I feel it needs to be checked.

**Comment by iaxat** [comment]
It has started happening again.

**Comment by xavluiz** [comment]
Thank you for the latest update. We'll look into profiling the latest version today to see what may be causing the issue.

**Comment by xavluiz** [comment]
The latest version, v2.5.24, has optimizations and general cleanup to perform efficiently. Please let us know if there are any more issues.
Regards.
