### ISSUE TITLE
can not login in the KDE de

### ISSUE THREAD

**Issue by cl3m3c7** [swdotcom/swdc-vscode#262]
**Describe the bug**
```paste below
not being able to login on the Linux (KDE)
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Click on 'Log in'
2. Select 'Log in with GitHub'
3. Enter login info in the GitHub page and get redirected to the user's dashboard
4. Nothing happened in the VsCode side!

**Expected behavior**
```paste below
See the user's data!
```

**ACTUAL RESULTS**

```paste below
Still seeing the Log in interface!
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux (KDE)
 - Plugin version 2.5.9

**Additional context**
```paste below

```

**Comment by xavluiz** [comment]
Hi @cl3m3c7 , can you try again with the latest version? v2.5.10.
The logic may have missed the auth event and this version has an update for that. Thank you.

**Comment by cl3m3c7** [comment]
Hello @xavluiz , yes it works again, but I get an error before I do log in:
![codetime-error](https://user-images.githubusercontent.com/61097104/113189810-85d1eb80-9253-11eb-9503-a8e1b79a348e.png)
every thing works good, but I just want to report about the error message I get before the login as well as a delay before the plugin view gets initialized! (when I clicked on the plugin icon, nothing show up for some time 30 seconds or so!)

**Comment by xavluiz** [comment]
Hi @cl3m3c7, thank you for the latest update and I'm glad you're able to login now. That prompt usually means our app was unreachable at the moment initialization happened or some other network issue. We'll look into this and we'll let you know if there's an update necessary for the plugin, thank you again.

**Comment by Taughtimp2786** [comment]
#362
