### ISSUE TITLE
Logging in with GitHub doesn't work

### ISSUE THREAD

**Issue by rileyjshaw** [swdotcom/swdc-vscode#264]
Note: this may be related to #220 or #262.

---

**Describe the bug**

```
Logging in with GitHub doesn't work.
```

**ISSUE TYPE**

    * Bug Report

**Steps to reproduce**

    1. Click on "Log in" in VSCode extension.

    2. Choose "Log in with GitHub"

    3. Browser window opens

    4. Log into GitHub

**Expected behavior**

```
Login applies to both the browser and the VSCode extension.
```

**ACTUAL RESULTS**

```
Login applies to the browser, but not to the VSCode extension.
```

**Desktop (please complete the following information):**

    * OS: macOS Version 11.2.3 (20D91)

    * Plugin version 2.5.9

    * Browser: I tried Firefox Developer Version (latest) and Chrome (latest)

**Comment by xavluiz** [comment]
Hi @rileyjshaw, can you try again with the latest version? v2.5.10.
The logic may have missed the auth event and this version has an update for that.  Thank you.

**Comment by rileyjshaw** [comment]
Yep, it seems to work now. Thank you!
