### ISSUE TITLE
Hide Flow Mode

### ISSUE THREAD

**Issue by ynifamily3** [swdotcom/swdc-vscode#267]
##### SUMMARY

```paste below
Please make sure to hide the Flow button in vscode.
```
![image](https://user-images.githubusercontent.com/13795765/115160609-1291fb80-a0d4-11eb-9655-6fd338a0a1a0.png)

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

```paste below

```

**Comment by brettmstevens7** [comment]
@ynifamily3 are you referring to the "Hide status bar metrics" button?

**Comment by ynifamily3** [comment]
My opinion is that preferences provide a way to hide the Flow status in the status bar.

**Comment by ynifamily3** [comment]
@brettmstevens7 My opinion is that preferences provide a way to hide the Flow status in the status bar.

**Comment by brettmstevens7** [comment]
Forgot to close this one, but it's been updated to hide the Flow status.
