### ISSUE TITLE
cannot connecting to visual studio code. when I click sign in from visual studio code, cannot return to my visual studio code after successfully login and cannot click connect to visual studio code from my software.com dashboard.

### ISSUE THREAD

**Issue by mnrendra** [swdotcom/swdc-vscode#269]
**Describe the bug**
```paste below

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by hirenpatel101** [comment]
I am also getting this on Windows, with v2.5.14 installed

**Comment by paulrm** [comment]
I am also getting this on Ubuntu, with v2.5.14 installed

**Comment by skamansam** [comment]
I am gettign this on Fedora Linux 34. Logging in just takes me to the login for the website and does not notify vscode in any way.

**Comment by xavluiz** [comment]
Hi, we apologize for the delay on this issue. We've updated the plugin websocket connection logic and fixed a minor error. Is this still happening with the latest version, 2.5.19? I will look into reproducing this today as well. If there are any errors visible from the developer tools console when logging in that would be helpful as well.
Thank you.

**Comment by Schtiel** [comment]
Same error, when you connect, it takes you to the web page, you connect and enter but visual studio does not connect 🙍‍♂️

**Comment by acecode116** [comment]
Just found this error... or something similar.  When I click "Log In" from the plugin in VS Code on Pop OS 21.04, it opens a tab in my browser, api.software.com/login/oauth... , but just header data is displayed, with "success" at the top and then my username, email, and such, in JSON format.  But it still doesn't login in my code editor.

**Comment by heyyod** [comment]
I just had the same issue only because I registered with my github account. I re-registered with google and it connected without a problem.

**Comment by Taughtimp2786** [comment]
Same issue on Arch Linux
