### ISSUE TITLE
How to manually set "I'm at work" or "I'm outside of work"?

### ISSUE THREAD

**Issue by gholami-mohammad** [swdotcom/swdc-vscode#27]
I added the configurations of working time in app.software.com, But sometimes I'm actually not at work and I'm at home. Maybe it's a holiday or anything else.
How can I config manually that where I am coding right now?
For a real example, these days I'm on holidays and coding at home on my own projects, but coding time will log in work time part!
I think, a small button in the editor can help set status: "I'm at work"!

**Comment by brettmstevens7** [comment]
Hi @m6devin - what if we added an advanced customization to designate your work vs. personal projects?

**Comment by m6devin** [comment]
@brettmstevens7 to separate time of personal project and get reports from that. You are making some reports from that in app.sofware.com.
For example `Work-life balance`. In this report work projects and personal projects are separated. But I know that some hours aren't belongs to work time and they are belongs to personal time.
I mean I can't be sure this report is showing a correct data! But with this option I can be sure that this plugin logged my time correctly.

**Comment by bjacobson26** [comment]
Thank you for the feature request. This has been added to our backlog.
