### ISSUE TITLE
Logs saved automatically, doesn't have code time, keystrokes, lines added data in VSCode

### ISSUE THREAD

**Issue by nasratt** [swdotcom/swdc-vscode#276]
**Describe the bug**
```paste below
When the VSCode code time extension creates and stores the log for the day automatically, 
clicking on the view logs option in VSCode doesn't show the stored code time, keystrokes, and added lines values.
But it seems that it is getting stored in the backend and I can see weekly code time when going to the Software.com website.
It seems that the data is not getting fetched from software.com.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Do not save the log for a day manually.
2. Go to view logs option of 100DaysOfCode extension.
3. The option will show all the logs, automatically saved logs will not have a title.
4. code time, keystrokes, and added lines will be shown as 0.

**Expected behavior**
```paste below
It should show the code time, keystrokes, and added line values on the logs view page.
```

**ACTUAL RESULTS**

```paste below
It shows the code time, keystrokes, and added line values all as 0.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/52889417/118775547-ace88900-b8a4-11eb-9783-fb3eff80be91.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Plugin version: 2.5.14

**Comment by DarkTamara** [comment]
Same issue here. I've been saving my log data manually for some time now.
