### ISSUE TITLE
The plugin does not allow to switch accounts

### ISSUE THREAD

**Issue by FilipaDurao** [swdotcom/swdc-vscode#278]
**Describe the bug**
Once I login on VSCode or Eclipse, I cannot change accounts, even when I click "switch account". It only takes me to the login page on the browser, I log in on the browser but on the IDE it does not change.

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
1. Log in (on either Eclipse or VSCode)
2. Try to switch account on "switch account"
3. The account does not change

**Expected behavior**
When one clicks "switch account" and logs in, the account should also log in on the IDE and not only on the browser.

**ACTUAL RESULTS**
The account does not change.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin version Code Time 2.5.14

**Comment by xavluiz** [comment]
Hi,
I apologize for the response delay and thank you for providing the issue details. I'll look at this issue right away, but if you uninstall Intellij does VSCode switch accounts correctly? I'll verify this using both plugins in the meantime.
Regards.

**Comment by FilipaDurao** [comment]
Thank you for your answer! I used both Eclipse and VSCode. In both, I tried uninstalling the plugin and reinstalling, and even tried uninstalling and reinstalling the IDE, none of which worked, once I install Code Time the account is still the same!

**Comment by xavluiz** [comment]
I apologize for the inconvenience but I'm currently unable to reproduce the issue with the plugins. There may be some sort of websocket connect issue that may be happening for your region as both Intellij and VSCode uses websockets to subscribe to the authentication event. We have Intellij updates we've been working on and will be publishing this version this week but I'd like to see if you would like to download the Intellij plugin from this branch to see if this fixes the current issue. Here's the github link to the softwareco.zip bundle. After downloading the zip, it can be installed locally from the Preferences->Plugins window by clicking the gear icon next to the "Installed" tab, and selecting "Install Plugin from Disk...". 

https://github.com/swdotcom/swdc-intellij/blob/impl-git-tracking/softwareco.zip

Thank you.

**Comment by xavluiz** [comment]
Hi @FilipaDurao,

We apologize for the delay. I've reproduced the issue and we should have a fix out very soon. Thank you for your patience.
Regards.
