### ISSUE TITLE
cannot register with any of the accounts (google,github) or email 

### ISSUE THREAD

**Issue by Pinche-Dev** [swdotcom/swdc-vscode#279]
cannot register 
I have made a software.com account from the domain itself but when I try to login from VS Code it doesnot work

OS: Kali Linux 2021.1
![image](https://user-images.githubusercontent.com/76829527/119232817-45e9ff00-bb46-11eb-922c-6112cbcd6c76.png)

**Comment by xavluiz** [comment]
Hi,
Thank you for the login information. We'll look at this right away.
Regards.

**Comment by xavluiz** [comment]
It looks as though you have a registered "github" account using a gmail email. If you're unable to log in using the github method, can you try removing your ~/.software folder, reloading your vscode window, then try using the "Log in" link under the "Register your account" to login via the GitHub method? It shouldn't take more than a few seconds but sometimes up to 15 seconds to complete authentication. What is your Code Time plugin version? Thank you.

**Comment by Pinche-Dev** [comment]
https://user-images.githubusercontent.com/76829527/119347845-ced67700-bcbb-11eb-82aa-83d76aaaed9e.mp4

**Comment by Pinche-Dev** [comment]
version::: v2.5.14

**Comment by Pinche-Dev** [comment]
also waited for more than 15 sec 
also logout  of vscode (github) and tried didn't work 
Thank you

**Comment by Pinche-Dev** [comment]
Thankyou for your support @xavluiz finally fixed
fix:
instead of using Snap version of VSCode use .deb package from https://code.visualstudio.com/download#

**Comment by xavluiz** [comment]
That's great to hear, and I will take note about the .deb package.
Regards.
