### ISSUE TITLE
Request: Option to hide or format statusbar text

### ISSUE THREAD

**Issue by darkvertex** [swdotcom/swdc-vscode#28]
I love tracking my coding but it's kind of a "personal" thing. When a supervisor or boss comes over my desk, I don't really want to be advertising publicly my numbers of the day and/or average, because they may pass judgement lacking context.

I would like a preference to hide the statusbar text. After all I can always get to the dashboard via the command panel (ctrl+shift+p) menu anyway.

Additionally, it could also be cool to have control over the formatting with a simple tokens system, so you can decide what number to show in the status or not, for example being able to show the hours coded today but not the 90 day average.

**Comment by brettmstevens7** [comment]
@darkvertex we loved both of these ideas and we're working on it. Thank you!

**Comment by bjacobson26** [comment]
Thank you for the feature request. This has been added to our backlog. 👍
