### ISSUE TITLE
Configure work hours 

### ISSUE THREAD

**Issue by reiko-dev** [swdotcom/swdc-vscode#281]
**Describe the bug**
```paste below
When clicking on the `Config work hours` the user is redirect to a 404 page.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Go to 'Configure settings'
2. Click on 'Configure work hours'
3. See a 404 page.

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**
![image](https://user-images.githubusercontent.com/9553743/119422034-782a6680-bcd6-11eb-91a0-3dec3eb8c4fe.png)

**Desktop (please complete the following information):**
 - OS: W10
 - VSCode v1.56.2
 - Code Time v2.5.14

**Additional context**
```paste below

```

**Comment by bjacobson26** [comment]
hi @reiko-dev - thank you for opening this issue. A fix has been deployed to production.

**Comment by reiko-dev** [comment]
@bjacobson26 you're welcome! =)
