### ISSUE TITLE
"command 'extension.codeTimeMetrics' not found"

### ISSUE THREAD

**Issue by miffycs** [swdotcom/swdc-vscode#29]
- Issue Type: `Bug`
- Extension Name: `swdc-vscode`
- Extension Version: `0.13.7`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.32.3`

Hi, I just installed Code Time, there was no alert prompting me to log in, and none of the commands listed for the command palette works:
```
extension.codeTimeMetrics
extension.softwareKpmDashboard
extension.viewSoftwareTop40
extension.codeTimeLogin
```

I'm on macOS Mojave, already made sure that my $PATH is correctly configured, don't have any issues with other extensions.

Please help!

**Comment by andrewhli** [comment]
Hi Miffy,

We’re glad you reached out. 

This is an issue that we’re not familiar with, so let’s work through it together. Could you please do the following?

1. Uninstall Code Time
2. Quit VS Code and any other editor/IDE you may have installed Code Time on
2. In your root directory, delete the .software hidden folder (this resets the connection, let me know if you have any questions finding this folder)
3. Reopen VS Code and install Code Time
4. If everything works, you’re good to go.
5. If it still doesn’t work, please email us the “session.json” file from the .software folder

We’ll get this fixed for you,

Andrew

**Comment by mimischi** [comment]
Same thing here. Uninstalling Code Time + restarting VS Code + Reinstalling Code Time does nothing, same error.

Following steps 1-4 in your description above (deleting `.software`). Fixes the error.

**Comment by antongiacomo** [comment]
> Same thing here. Uninstalling Code Time + restarting VS Code + Reinstalling Code Time does nothing, same error.
> 
> Following steps 1-4 in your description above (deleting `.software`) fixes the error.
> 
> Edit: The problem reappears after switching workspaces.

Same here, the problem reappears

**Comment by wickeym** [comment]
I'm also having this issue, it appeared yesterday right after I did a liveshare, though I don't know if that was just coincidence, since it seems others are also encountering the issue.

**Comment by xolott** [comment]
Yesterday it was working fine. Today, I sit again to work an it was no longer working (Restarted VSCode, reinstalled Code Time, restarted the pc, nothing fix it)

**Comment by andrewhli** [comment]
Hi everyone, yesterday we introduced a new bit of logging to diagnose and fix another issue. I’m thinking that extra metric is causing these problems, especially because problems seem to reappear after switching workspaces, livesharing. We’re jumping on this now, and I’ll let you know when it’s fixed.

**Comment by brettmstevens7** [comment]
We fixed the issue where Code Time was not properly loading when switching workspaces. 

@miffycs - when you install v0.13.9, do you still see the issue you described where the 4 command menu items don't work?

**Comment by miffycs** [comment]
@andrewhli @brettmstevens7
Thanks for the swift reply! Just tried your instructions and it works!!
Also tried switching directories and it's still good!

Saw the dashboard for the first time, the visuals are amazing, thank you for all your help, keep up the good work!!
