### ISSUE TITLE
Time counter does not work in status bar

### ISSUE THREAD

**Issue by omidmokhtari93** [swdotcom/swdc-vscode#291]
Time counter does not work in status bar. but working in dashboard. seems status bar does not update. when reload vscode, it updates

**Comment by inn3rs3lf** [comment]
Having the same issue. 
![Screenshot 2021-06-25 at 22 11 18](https://user-images.githubusercontent.com/59938871/123480212-4c1a4200-d602-11eb-8b56-e909a9d2f880.png)
![Screenshot 2021-06-25 at 22 11 11](https://user-images.githubusercontent.com/59938871/123480215-4de40580-d602-11eb-9f55-598a2a4321f1.png)

**Comment by mmclead** [comment]
@omidmokhtari93 @inn3rs3lf This PR:  https://github.com/swdotcom/swdc-vscode/pull/296 has the fix for this issue.

We'll have this out in an update soon.
