### ISSUE TITLE
Custom Webhook for Flow Mode

### ISSUE THREAD

**Issue by 4nkitd** [swdotcom/swdc-vscode#292]
##### SUMMARY

```paste below
    a user can add a webhook on flow mode state change
```

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

```paste below
 payload can be any of post/get and support payload with headers.
```

**Comment by mmclead** [comment]
We've built this functionality, and more with our newest extension EditorOps

https://marketplace.visualstudio.com/items?itemName=softwaredotcom.editor-ops

Check it out!
