### ISSUE TITLE
I think need to show code time of last 1 year.

### ISSUE THREAD

**Issue by shafinthedeveloper** [swdotcom/swdc-vscode#297]
##### SUMMARY

```paste below

```

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

```paste below

```

**Comment by bjacobson26** [comment]
Hi @shafinthedeveloper -

Thank you for the suggestion. We currently only provide 90 days of code time history for our free plan. 

Our [individual pro plan](https://www.software.com/pricing) allows individuals to generate code time reports with custom ranges. Here is what my last year looks like:

![image](https://user-images.githubusercontent.com/9271952/124676541-95288c80-de73-11eb-87fb-696c12f67fd4.png)
