### ISSUE TITLE
Does not count time on Reactjs and Django

### ISSUE THREAD

**Issue by satya-sudo** [swdotcom/swdc-vscode#298]
# Issues
- The plugin stays on 0 unless clicked on dashboard  on every launch of VSCode
- Does not count time when working with reactjs or django  unless  a reload of the plugin
- fails to load the dashboard few times through out the day

**Comment by mmclead** [comment]
Hi @satya-sudo the timer is still tracking.    The issue you are seeing is being resolved in the open pull request https://github.com/swdotcom/swdc-vscode/pull/296.  We continually sync the timer with a web socket connection and when it disconnects, we currently aren't reconnecting it.   That results in the clock staying at zero.   

We'll have that fixed up this week.

Thanks for using the plugin!
