### ISSUE TITLE
Account Login does not work correctly with Google or Github

### ISSUE THREAD

**Issue by skamansam** [swdotcom/swdc-vscode#299]
**Describe the bug**
```
When clicking the `Log In` link from the sidebar panel "Getting Started with Music Time," it takes me to the login page for the website. After logging in with either the google login or the github login, it redirects me to the website instead of sending a link for vscode login.
```
**ISSUE TYPE**
- Bug Report
- Breaks all functionality

**Steps to reproduce**

1. Install the Music Time extension in VSCode
2. Open the Music Time panel
3. Click on the `Log In` link in the colored box titled "Gettign Started with Music Time"
4. Select either the "Log in with Google" or "Log in with Github" option in the resultant window.
5. Authenticate via the Oauth screens that appear

**Expected behavior**
```
After logging in, VSCode should be notified that I am  logged in and start populating the music browser.
```

**ACTUAL RESULTS**

```paste below
After logging in, I am taken to the website dashboard and VSCode is *not* notified I am logged in nor does anything else happen in VSCode.
```

**Screenshots**
![LoggingInWithMusicTime](https://user-images.githubusercontent.com/102971/124807616-f90e8c00-df2b-11eb-9d98-bbbc46dbedd6.gif)

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Plugin version 2.2.16

**Additional context**
```paste below
I am already loggin in to Google, Github, and the Music Time website.
```

**Comment by xavluiz** [comment]
Hi,
Thank you for the issue update. We'll look into this today.
Thank you.

**Comment by xavluiz** [comment]
@skamansam,
Is this issue specific for Music Time or are you also having issues connecting using Code Time?

Thanks,
Xavier

**Comment by xavluiz** [comment]
Hi @skamansam,
Music Time has been updated to v2.2.17 to fix a minor error and an update to fetch the user information. We're still looking into why the websocket logic did not update your editor. Would you be able to try the latest version to see if it fixes your issue? Thanks.

**Comment by xavluiz** [comment]
We'll close this ticket for now, but if this is still an issue for you we can open a new one. Thank you.

**Comment by Gies7** [comment]
Hi, new user here.
I am currently running into this issue using code time.
The VSCode extension does show up in the 'data sources' tab, but i can't log in in VSCode.
I am logging in using email.

If there is any other information I can provide, please don't hesitate to ask.

**Comment by xavluiz** [comment]
Hi,

I will investigate this issue and get back to you. Thank you for the
information in regards to the login type that is used.

Thank you.

**Comment by xavluiz** [comment]
Hi,
We've looked into it and currently have a pull request to fix the issue.
I'll update you as soon as we have this resolved and thank you for your
patience.

Regards.

**Comment by Gies7** [comment]
Hi, thanks for your quick response!
Looking forward to hear from you!

**Comment by xavluiz** [comment]
We apologize for the delay in getting this fix in. It's currently in our
staging environment for validation and should move into production later
today, but I'll let you know as soon as this is done.

Thank you again for your patience.

Regards.

**Comment by xavluiz** [comment]
Hi,
We've applied the update on our app and signing up via email should now be
working. Thank you.

Regards,
Xavier

**Comment by Gies7** [comment]
Hello,
I am still unable to login using email.
Logging in with google does work for me now, thanks.
