### ISSUE TITLE
Streaks

### ISSUE THREAD

**Issue by brancifortnick** [swdotcom/swdc-vscode#300]
I haven't logged my daily coding data, so I am wondering if this has something to do with my streaks being stuck at 1 day.  I code almost everyday, and would appreciate the certificate! Please let me know how to earn this

**Comment by xavluiz** [comment]
Hi @brancifortnick,
We've published the latest version, v2.5.23, to help with consistent tracking. Are you still having issues with your code time information?
Thanks.
