### ISSUE TITLE
Do not track time with unstable internet connection

### ISSUE THREAD

**Issue by frusanov** [swdotcom/swdc-vscode#306]
**Describe the bug**
I have very unstable LTE connection and when it's going very bad, extension don't track my time. I can work all day but it tracks only small part of time that I spend in VS Code.

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

Have internet connection that sometimes does not work at all.

**Expected behavior**
Track all my time

**ACTUAL RESULTS**
Tracks only part of it

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Home Edition
 - Code Time 2.5.19
 - VS Code 1.58.2

**Comment by xavluiz** [comment]
Thank you for the issue update. We'll look into a solution for this today.

**Comment by magdy-ragab** [comment]
+1
I've the same problem

OS : Ubuntu 20.04.2 LTS
VS Code: 1.58.2
Code Time: 2.5.21

**Comment by DarkTamara** [comment]
Same here, two days ago it worked well and recorded my data but today it won't track my time at all.

**Comment by xavluiz** [comment]
We're working on a solution to help with offline usage and should have the update available very soon. @DarkTamara do you also have connectivity issues or do you see any other type of issues via the dev tools console? Thanks.

**Comment by xavluiz** [comment]
We v2.5.23 to support time tracking for this use case. Please let us know if there are any other issues. Thank you.

**Comment by chachan** [comment]
Still seeing this problem. I usually get connected/disconnected into companies VPN and seems like tracking just stops
