### ISSUE TITLE
Does not count time on .ipynb extension (jupyter notebook)

### ISSUE THREAD

**Issue by satya-sudo** [swdotcom/swdc-vscode#311]
**ISSUE TYPE**
- Bug Report
- The extension does not count time for files with .ipynb (jupyter notebook)

Desktop 
 - OS: [e.g. pop os  21.04]
 - Plugin version [e.g. Code Time v2.5.21]

**Comment by HGladiator** [comment]
pls must solve this problem! thx, i love this plugin very much!

**Comment by xavluiz** [comment]
Thank you for your patience. We've launched v2.6.1 to fix this issue, along with performance optimizations. Let us know if there are any other issues, thank you.
