### ISSUE TITLE
Code time for the current day shows as NaN

### ISSUE THREAD

**Issue by pmayur** [swdotcom/swdc-vscode#313]
**Describe the bug**
```paste below
- On Code Time dashboard the time comparison with 90 day avg displays todays time as NAN m
- This is an issue only under the today section only
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Click on CodeTime extension
2. Click on Dashboard
3. On load under dashboard the time for today shows as NaN m in comparison section only

**Expected behavior**
```paste below
- The time value should show whatever time has been spent instead of NaN
```

**ACTUAL RESULTS**

```paste below
- The comparison time value is showed as NaN
```

**Screenshots**
![Screenshot from 2021-08-06 18-17-52](https://user-images.githubusercontent.com/25099080/128519514-14b8086a-3157-49e1-b137-70213317d2fe.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]: Ubuntu 20.04
 - Plugin version [e.g. Code Time v1.2.1]: Code Time v2.5.21

**Comment by xavluiz** [comment]
Hi @pmayur,
We've had latency issues fetching this data but this is now resolved. Is this still an issue for you.?

Thanks.

**Comment by pmayur** [comment]
thanks for acknowledging @xavluiz, after checking again this is not an issue anymore.
