### ISSUE TITLE
1

### ISSUE THREAD

**Issue by danielebjj** [swdotcom/swdc-vscode#314]
##### SUMMARY

```paste below

```

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

```paste below

```

**Comment by danielebjj** [comment]
> ##### SUMMARY
> ```
> 
> ```
> 
> ##### ISSUE TYPE
> * Feature Request
> 
> ##### ADDITIONAL INFORMATION
> ```
> 
> ```

**Comment by xavluiz** [comment]
Hi @danielebjj,
Is there a feature you'd like to request? Thanks.
