### ISSUE TITLE
Logs,Milestones etc. not opening in vscode extension

### ISSUE THREAD

**Issue by itsmeshibintmz** [swdotcom/swdc-vscode#315]
**Describe the bug**
```
In VS Code Extension, View logs, View Milestones are not opening. I cannot create a new log entry.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Go to ' VS Code 100 days of Code Extension '
2. Click on 'View Logs, view Milestones'
3. Nothing opens.

**Expected behaviour**
```Should be able to view logs, create a new log entry.

```

**ACTUAL RESULTS**

```Noting opens

```

**Screenshots**
![image](https://user-images.githubusercontent.com/52344717/129499001-358001e7-1141-48ff-af98-2508a8eb0770.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Plugin version [e.g. Code Time v1.2.1]

```

**Comment by warmijusti** [comment]
Same here.... it is a pity, this looks like a good extension. And I couldn't find this same functionaliti in Code Time (registering logs)

**Comment by itsmeshibintmz** [comment]
> Same here.... it is a pity, this looks like a good extension. And I couldn't find this same functionaliti in Code Time (registering logs)

This issue is caused by 100 days of Code extension. It is no longer maintained, only codetime is working now.
