### ISSUE TITLE
Can't login to VSCode plugin on Debian

### ISSUE THREAD

**Issue by m6devin** [swdotcom/swdc-vscode#32]
Everything was OK on Debian, But I've updated my VsCode and now, codetime plugin can't login.
Here is details of VsCode version:
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-8-amd64
```
and this is the error I've gotten in vscode's developer tools:
```
Code Time: error fetching data for /users/plugin/state, message: Request failed with status code 500
```
Codetime plugin version is 0.14.5

When I hit login button on vscode, it will redirect me to this URL: `https://app.software.com/onboarding?token=null`.

**Comment by neogan74** [comment]
The same for me on Win10. No stats locally. It seems doesn't login at all. 
Probably need some token to put it manually in such cases.

**Comment by m6devin** [comment]
I've updated CodeTime plugin to v0.15.0 and the probleme solved! Now I'm login.
I lost these 11 days logs!
