### ISSUE TITLE
Selectboxes look broken in the Windows 10 (dark theme)

### ISSUE THREAD

**Issue by aykutkardas** [swdotcom/swdc-vscode#326]
**Describe the bug**

```paste below
When I check from a Windows 10 computer in dark theme, I see the selectboxes broken.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Use `Windows 10 with Dark Theme`
2. Click on 'Configure Settings in CodeTime Extension'
3. Check 'any selectbox'

**Screenshots**
![image](https://user-images.githubusercontent.com/7966133/132819969-dec537bd-6346-486e-9f58-9d60f819a945.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Dark Theme)
 - Plugin version [Code Time v2.5.24]

**Comment by mmclead** [comment]
This is fixed now.  Please let us know if you see the issue again.
