### ISSUE TITLE
Define work\personal code by project

### ISSUE THREAD

**Issue by magdalipka** [swdotcom/swdc-vscode#328]
##### SUMMARY

Right now we can specify work/personal coding time only by setting work hours (at least that's the only way I'm aware of, please correct me if I'm wrong). It would be great do be able to define work/personal code per project

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

This would be super useful for people working flexible hours. User can specify that certain projects are work-related and others would be treated as personal.

**Comment by bjacobson26** [comment]
[The Reports feature](http://app.software.com/code_time/reports) can be used to break down code time by projects / repos
