### ISSUE TITLE
Key binding conflict

### ISSUE THREAD

**Issue by amielucha** [swdotcom/swdc-vscode#33]
I encounter an issue with the following functionality:

> Toggle the Code Time status bar metrics (ctrl+c ctrl+t)

This binding converts CTRL+C keyboard shortcut to a chord, preventing its default function of copying highlighted text.

I suggest changing the default key binding to a combination starting with CTRL+K.

Tested in VSCode 1.33 on Linux.

**Comment by Dzejkop** [comment]
I'm also experiencing this issue on Windows

**Comment by sattellite** [comment]
I reassigned the hotkey combination <kbd>CTRL</kbd>+<kbd>C</kbd> <kbd>CTRL</kbd>+<kbd>T</kbd> to another combination and copying began to works.
It was ambiguous problem.

**Comment by andrewhli** [comment]
We pushed a fix for this on v0.14.7 (shortcut is now Ctrl-T). Apologies for the bug. Someone from our team pushed Ctrl-C yesterday without awareness of the conflict it would cause.

**Comment by OpenCode** [comment]
@andrewhli @amielucha If you set "CTRL+T CTRL+C" instead "CTRL+C CTRL+T" it work with no problems.

**Comment by amielucha** [comment]
> We pushed a fix for this on v0.14.7 (shortcut is now Ctrl-T).

By default CTRL+T is "Go to symbol in Workspace..." Are you sure this is the best shortcut to override? I think it's better to leave it up to the user and keep the command unbound.

**Comment by andrewhli** [comment]
That's a good idea. We'll create a fix that leaves it up to the user.

**Comment by Barben360** [comment]
Same thing here, had to reassign the shortcut.

**Comment by andrewhli** [comment]
Wanted to give an update: In the latest version of Code Time (v0.14.9) we've removed the keyboard shortcuts. To toggle the Code Time metrics in the status bar display:on/off, please click the last link in the dropdown menu. Once the metrics are toggled display:off, you'll see a clock icon in the status bar, which you can click to toggle the metrics to display:on

<img width="604" alt="Screen Shot 2019-04-18 at 11 22 08 AM" src="https://user-images.githubusercontent.com/5068143/56382540-7b37fc00-61cc-11e9-9c9a-98d78bfed835.png">
