### ISSUE TITLE
"Unable to generate view." after "Code Time Settings" tab opens

### ISSUE THREAD

**Issue by darkvertex** [swdotcom/swdc-vscode#333]
**Describe the bug**

Whenever I try open the Code Time Settings tab, it stays blank and I get:

![image](https://user-images.githubusercontent.com/941331/135685854-3d322ddd-494a-408a-996e-7a3d6ff76f3c.png)

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Open panel.
2. Click on gear icon.
3. "Code Time Settings" tab opens, but remains blank.

**Expected behavior**
I expected settings to appear.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19042 x64
 - VSCode: 1.60.2
 - Plugin version: Code Time v2.5.26

(Maybe reinstalling might fix it, but I thought maybe you'd want to investigate some logs before I do that.)

**Comment by bjacobson26** [comment]
hi @darkvertex - thank you for reporting the issue. we're currently looking into it. will update once we're back up.

**Comment by bjacobson26** [comment]
@darkvertex this should be resolved. please reopen if you continue to have issues. thank you!

**Comment by darkvertex** [comment]
I confirm I can open the settings now. Thanks for the quick fix! 👍
