### ISSUE TITLE
offline use

### ISSUE THREAD

**Issue by prydda** [swdotcom/swdc-vscode#34]
I noticed yesterday that code time dont send stats if there is no network connection.. 
Now it looks like I didn't work anything yesterday. 

Would it be possible to store this data in json locally when working offline. Then when you get back to a less remote location with internet connection it sends the data to the server?

**Comment by tehshane** [comment]
It seems like there have been an increasing number of outages in the service lately. This would be a great feature to help take the pressure off.

**Comment by andrewhli** [comment]
Hi @tehshane and @prydda. We are working on the features to store the data locally, so that your data will be available and recorded even during an outage. We apologize for the recent outages.

**Comment by gangstead** [comment]
I had this problem too and I noticed that [WakaTime](https://wakatime.com/) aleady has this

**Comment by bjacobson26** [comment]
This issue is resolved. Thank you!
