### ISSUE TITLE
Automatically go into Flow Mode

### ISSUE THREAD

**Issue by moeen-mahmud** [swdotcom/swdc-vscode#355]
**Describe the bug**

```
It goes into flow mode automatically even if I disable the Automatic Flow Mode option.
```
**ISSUE TYPE**
- Bug Report

**Expected behavior**
```
It should not automatically go into flow mode. It will go into that when the option is enabled.
```

**Screenshots**
![code_time_bug](https://user-images.githubusercontent.com/61315959/140651566-3272663e-4883-40b4-b551-78bb6d0b70a7.png)

**Desktop:**
 - OS: Windows 10 pro
 - Plugin version: 2.6.8

**Comment by thamudi** [comment]
Same here, I have it disabled in my settings but it keeps going into flow mode regardless.

And another issue is that if i had  multiple instances of VS code open. All of them will go into flow mode even though I am working on one Project.

**Comment by moeen-mahmud** [comment]
Yeah, you are right! The same thing happened to me also, but I forgot to mention it before. 
I did a quick fix though.
 
Here, I turned the **Screen Mode** to _none_. So, it doesn't change my screen to the **Zen Mode**. 

![Code_XiRi5VRLyA](https://user-images.githubusercontent.com/61315959/140776787-7a8419c1-c1b7-44e4-8dd3-1ae8bed4302f.png)

**Comment by mmclead** [comment]
Thanks for reporting.  I'll have a fix going for this shortly.  I see the issue.

**Comment by p4u1d34n** [comment]
Same here :)

**Comment by moeen-mahmud** [comment]
> Thanks for reporting. I'll have a fix going for this shortly. I see the issue.

Thanks for being aware of the matter. I hope you will fix the problem soon. 💙

**Comment by ENTPRESTIGIOUS** [comment]
Same here also and it's really bothering me when i'm coding.

**Comment by moeen-mahmud** [comment]
> Same here also and it's really bothering me when i'm coding.

I have shown a quick fix above. 👆
You can follow that until it is fixed.

**Comment by thamudi** [comment]
@moeen-mahmud I did try that as well, but it didn't work for me, it still goes into flow mode.
I will wait until the bug is fixed.

**Comment by mmclead** [comment]
I just tested the fix in Staging.  Its performing well and I'll have it out to production shortly.

**Comment by mmclead** [comment]
Fix is in production now.   I'll check in on this tomorrow to resolve the issue if its working well for y'all.

**Comment by mmclead** [comment]
> Same here also and it's really bothering me when i'm coding.

Sorry it was bothering your when coding.  It's specifically designed to help, not hurt, so my apologies about the disruption.   Should be all set now.

**Comment by moeen-mahmud** [comment]
@mmclead Thank you so much for fixing the bug so quickly.

**Comment by mmclead** [comment]
I'll be closing this issue now that the fix is in production.   

Please reopen if you continue to have this issue.
