### ISSUE TITLE
vscode shows getting started even though I am already signed in

### ISSUE THREAD

**Issue by TMJSMC53** [swdotcom/swdc-vscode#356]
**Describe the bug**
```paste below

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by TMJSMC53** [comment]
Good afternoon, I don't know if anyone else if having this issue, but it hasn't been fixed. I can't see the dashboard that used to be there when i clicked on the icon in vscode. I have uninstalled and reinstalled this app twice already, however, the problem still exists. Is there an eta on this matter?

**Comment by bjacobson26** [comment]
Hi @TMJSMC53 - sorry for the delay. Are you still experiencing this issue?

**Comment by TMJSMC53** [comment]
Hey Bo,

Good afternoon. Originally, I was working with Geoff and then he stopped
replying, so I just deleted my account and the extension. Dealing with the
issue was getting in the way of my workflow. Maybe I'll come back later on.
Thanks for replying.
Ciao,

TMJ

**Comment by TMJSMC53** [comment]
I decided to just delete my account and extension.
