### ISSUE TITLE
Cant able to track code time

### ISSUE THREAD

**Issue by ikismail** [swdotcom/swdc-vscode#36]
**VSCode Version:**

![image](https://user-images.githubusercontent.com/17190913/57099657-96614a80-6d3a-11e9-8e47-1de800da2b74.png)

**Operating System:**
![image](https://user-images.githubusercontent.com/17190913/57099747-d1fc1480-6d3a-11e9-8f8a-9561031d0b6a.png)

Code Time stopped working, 
telling me to login, I have already logged in 

![image](https://user-images.githubusercontent.com/17190913/57099573-62862500-6d3a-11e9-9432-7189a214f7c0.png)

but still I see

![image](https://user-images.githubusercontent.com/17190913/57099616-7b8ed600-6d3a-11e9-9806-564aba6688ef.png)

**Comment by brettmstevens7** [comment]
Hi, sorry for the hassle. Could you send me an email at brett@software.com with your session.json file in your .software folder (in your home directory)? It would help to see if your JWT has changed.

After you've done that, delete your .software folder, restart VS Code, and click log in to reconnect your account. Let me know if that works and you're able to send data to your email account.

**Comment by brettmstevens7** [comment]
Following up on this, you might have a corrupted `session.json` file, maybe from an older version of our plugin. We pushed an update that should fix the issue. Here are the steps to log in:

* Delete the `session.json` file in your `.software folder` in your home directory
* Restart VS Code to download the latest version of Code Time 
* Click on the login prompt or menu command to log in at the /onboarding URL.
* You should now be logged in. If you go to your `session.json` file, you should now see a JWT and name field with your email. You can also hover over your status bar to see your email.

**Comment by ikismail** [comment]
@brettmstevens7  thanks, solved my issue 👏
