### ISSUE TITLE
Code Time not connecting

### ISSUE THREAD

**Issue by Taughtimp2786** [swdotcom/swdc-vscode#362]
**Code time not connecting**
"Service temporarily unavailable", it says, despite being shown up in https://status.software.com/

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
Start Visual Studio Code, and get the notification:

![Screenshot_20211113_120457](https://user-images.githubusercontent.com/77712873/141608844-6e13d514-77f4-42a8-944e-d9f43b35c577.png)

**Expected behavior**
Code time should open up like this when clicked on the side bar button of code time:

![Screenshot_20211113_120902](https://user-images.githubusercontent.com/77712873/141608908-4cdb10c6-b66c-4117-ac17-b3ea87d1c4e3.png)

**ACTUAL RESULTS**
Service temporarily unavailable

![Screenshot_20211113_121039](https://user-images.githubusercontent.com/77712873/141609031-5e9bf21b-a943-4940-bc79-9a8590eedc47.png)

**Desktop (please complete the following information):**
 - OS: Arch-Linux-x86_64
 - Plugin version: Code-Time v2.6.14
 - Visual Studio Code version: v1.62.2 (Snap Package)

**Comment by xavluiz** [comment]
We apologize for the delay. Is this still an issue? We're not experiencing any server issues. Please let us know and we'll look into this, thank you.

**Comment by Taughtimp2786** [comment]
Yes this is still an issue.

**Comment by RainbowCookie32** [comment]
Also had this issue on Arch Linux. Saw that the extension was complaining on the Output tab about not being able to execute `hostname`, so I installed the `inetutils` package, which provides it and it seems to have fixed the issue.

**Comment by Taughtimp2786** [comment]
> Also had this issue on Arch Linux. Saw that the extension was complaining on the Output tab about not being able to execute `hostname`, so I installed the `inetutils` package, which provides it and it seems to have fixed the issue.

I installed the package, and enable kde wallet. Somehow, code time actually connects now.
