### ISSUE TITLE
Login or signup button does nothing.

### ISSUE THREAD

**Issue by RaiSaugat** [swdotcom/swdc-vscode#367]
**Describe the bug**
```paste below
When I click login or signup button, nothing happens

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**
**Desktop (please complete the following information):**
 - OS: Pop Os 21.01
 - Plugin version v2.6.16
 - 

**Additional context**
```paste below

```

**Comment by bjacobson26** [comment]
Hi @RaiSaugat - are you still experiencing this issue? If so, can you please provide a screenshot? Thank you.

**Comment by mrstebo** [comment]
@bjacobson26 I also experience this issue. Do you think it could be an issue with the `open` NPM package? It is used in [this](https://github.com/swdotcom/swdc-vscode/blob/main/src/Util.ts#L357) function.

I could spin up a small electron app on Linux to investigate if that is the case.

**Comment by rullydamara** [comment]
cant login in windows 10

**Comment by RaiSaugat** [comment]
![image](https://user-images.githubusercontent.com/19557538/155940333-16fa7c49-c1e3-4c29-bd46-b0a2561c6a63.png)
After clicking the signup or login, nothing happens.

**Comment by zhtjtcz** [comment]
I have this problem too. Do you have a solution?
