### ISSUE TITLE
Unable to find usage of Blake2B in the repo src

### ISSUE THREAD

**Issue by KShivendu** [swdotcom/swdc-vscode#372]
Hi, 
I was trying to find where exactly the Blake2B algorithm has been used to encrypt our data. But I couldn't find it by searching for the relevant keywords. It's clearly present in `swdotcom/swdc-visualstudio` and `swdotcom/swdc-sublime` but I couldn't find it in this repo. Could you please help me find it so that I can be confident about data privacy?

**Comment by mmclead** [comment]
Let me know if that doesn't answer your concerns, and happy coding!
