### ISSUE TITLE
Cannot log in on Ubuntu 20.04

### ISSUE THREAD

**Issue by florinrelea** [swdotcom/swdc-vscode#375]
**Describe the bug**
```
Cannot Log in on Ubuntu 20.04
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
[Video](https://streamable.com/yoiyot)

**Expected behavior**

```
Redirect to login page
```

**ACTUAL RESULTS**

```
Nothing
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Plugin version: Latest

**Comment by mrstebo** [comment]
I am also getting this issue. There is also #367 that mentions this issue, which also appears to be a Linux distro :thinking:

**Comment by Quark03** [comment]
Exact same issue here - Also Ubuntu 20.04
