### ISSUE TITLE
When I install and open the extension it shows nothing but a blank screen.

### ISSUE THREAD

**Issue by shreedharhegde99** [swdotcom/swdc-vscode#387]
It shows nothing but like this ....empty screen

![Screenshot from 2022-01-27 07-48-11](https://user-images.githubusercontent.com/90758718/151281401-7d8fdcb2-c774-454c-b1df-832837c2f274.png)

**Comment by Ianodad** [comment]
I have the same problem

**Comment by Scottzonn** [comment]
So do I

**Comment by nandez** [comment]
Same here. I think this may be related to #345 

In my case:

- OS: Windows 10 Pro 21H2 (19044.1526)
- VSCode: 1.64.2
- Electron: 13.5.2

From vscode Extension Host logs i can see the follwing error:

> [2022-02-17 19:12:00.560] [exthost] [info] ExtensionService#_doActivateExtension softwaredotcom.swdc-vscode, startup: false, activationEvent: 'onStartupFinished'
> [2022-02-17 19:12:01.075] [exthost] [error] Activating extension softwaredotcom.swdc-vscode failed due to an error:
> [2022-02-17 19:12:01.121] [exthost] [error] RangeError: Maximum call stack size exceeded
> 	at splitPath (electron/js2c/asar_bundle.js:5:781)
> 	at Object.e.existsSync (electron/js2c/asar_bundle.js:5:6148)
> 	at T (c:\Users\nande\\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.27\dist\extension.js:1:887361)
> 	at k (c:\Users\nande\\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.27\dist\extension.js:1:887048)
> 	at F (c:\Users\nande\\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.27\dist\extension.js:1:887191)
> 	at E (c:\Users\nande\\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.27\dist\extension.js:1:886491)
> 	at H (c:\Users\nande\\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.27\dist\extension.js:1:887635)
> 	at P (c:\Users\nande\\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.27\dist\extension.js:1:887500)
> 	at i (c:\Users\nande\\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.27\dist\extension.js:1:912038)...

**Comment by nandez** [comment]
@xavluiz , I got an attempt to fix this issue on this PR [#395 - Updated FileManager.getFileDataAsJson to trim string prior parsing.](https://github.com/swdotcom/swdc-vscode/pull/395). Please let me know if this works for you.

**Comment by devxbasit** [comment]
@nandez  I also have the same issue, shows the loading progress bar only
![image](https://user-images.githubusercontent.com/24441401/164990554-9f716e4d-4fbf-4218-915a-662bfba35ae0.png)

**Comment by xavluiz** [comment]
Great, thanks for the update. I'll test this out today.

Regards,
Xavier

**Comment by buneeIsSlo** [comment]
Hi, this issue still exists. Any updates?

**Comment by fernando24j** [comment]
Still going on

**Comment by nandez** [comment]
Hey guys, how are you doing? So sad to know that this is still happening.
May I ask you to provide some info?

Could you check the "Extension Host" logs and look for any error related to this extension?
Just in case `cmd-shift-p` -> Search `Show Logs` -> `Extension Host`

You should see something like this (and hopefully, in case of an error, some trace to help)
![imagen](https://user-images.githubusercontent.com/1672704/187554898-c44d408a-3431-468f-afd6-7dd5d30042ce.png)

Even better, you can get your log file and attach it:
![imagen](https://user-images.githubusercontent.com/1672704/187555246-94f52e63-efd1-4d5d-85d3-93f421e47da0.png)

![imagen](https://user-images.githubusercontent.com/1672704/187555438-4ee093a8-4480-4af9-8742-1c502b7a5d9b.png)

Many thanks!

**Comment by buneeIsSlo** [comment]
Hi @nandez, I hope this helps.
[exthost.log](https://github.com/swdotcom/swdc-vscode/files/9482624/exthost.log)
