### ISSUE TITLE
Account was created with incorrect email

### ISSUE THREAD

**Issue by alexjurkiewicz** [swdotcom/swdc-vscode#389]
**Describe the bug**
It appears I have hijacked another user's account. Perhaps there is a bug or race condition during your signup flow.

I installed the Code Time vscode extension about a week ago. I opened the control panel to check my stats and noticed it says my email address is `wuboxin98@qq.com`. That's not my email and I've never seen it before in my life!
<img width="1648" alt="Screen Shot 2022-02-02 at 4 23 42 pm" src="https://user-images.githubusercontent.com/379509/152097691-dd44795b-d0e2-4e36-aa1c-50e117d15e2b.png">

When I visit https://app.software.com/account and check the drop down menu in the top right, the email also shows as this @qq.com domain. However, the account has otherwise been customised by me. For example, setting my name, work hours, and connecting my google calendar.

I also have the github app installed on my profile, but the account settings page shows a badge to "link your github profile".

Please let me know what other info you need.

**Comment by xavluiz** [comment]
Hi @alexjurkiewicz,
We apologize for the issue. We'll look into this right away, but in the meantime, have you tried the "account switch" option next to the "Account" header within the sidebar? If this isn't switching to your correct account you can delete the ".software" folder under your home directory and refresh vscode to allow the plugin to re-initialize the session. You will not lose any code time data but will need to login again from the plugin. We'll let you know as soon as we find out more. Thanks.

**Comment by xavluiz** [comment]
HI @alexjurkiewicz

We've identified the issue and released a patch.  We've had a rare ID collision and have updated how the plugin authenticates with our app. This is now available in code time v2.6.27 and later. Unfortunately, this means the <user_home>/.software will need to be deleted and the vscode editor refreshed. After that you can log in again. We apologize for inconvenience.

Regards.

**Comment by alexjurkiewicz** [comment]
Thank you!
