### ISSUE TITLE
Code time doesnt count hours spend on project

### ISSUE THREAD

**Issue by ChrystianC** [swdotcom/swdc-vscode#394]
I istalled code time couple days ago and its  doesnt count time in project . I need enable it somewhere or it analizing langueage and its not supported

**Comment by comphonia** [comment]
They used to have it, and now put it behind a pay-wall I believe. Time to uninstall!

**Comment by mattpenner** [comment]
Agreed, I installed the plug-in for the first time and created an account a few days ago. After several hours of programming I'm not seeing anything at all in the stats.  Global Active Code/Meeting time seems to show up but I don't know what numbers those are.  They aren't mine.

There isn't much documentation about how this works and I can't find anything on how they gather data. Not sure if I am supposed to enable something or not.

**Comment by ChrystianC** [comment]
@mattpenner  same now i using time master but i have to change default formating and now it work flawlessly

**Comment by mattpenner** [comment]
Thanks @ChrystianC. I looked at time master and it seems neat but one of my needs is to view stats in a dashboard style on our project website.  So after some looking around I've settled on Waka Time for now.  It also integrates with BitBucket, which is our repo host for projects.  So far looks promising. Too bad this thread has to be on the Code Time github but hope it will help others who are in the same situation.

**Comment by bjacobson26** [comment]
If you are on a paid plan, you should be able to see your code time broken down by projects at https://app.software.com/reports

are there any particular project related graphs or visualizations you'd like to see on the code time dashboard?
