### ISSUE TITLE
'CreateInstance failed' error on Visual Studio 2019

### ISSUE THREAD

**Issue by TheNetos** [swdotcom/swdc-vscode#397]
**Describe the bug**
I'm install extension from [microsoft marketplace](https://marketplace.visualstudio.com/items?itemName=softwaredotcom.Software)
Install done succesfully.

But on running Visual Studio i'm see that message:

![image](https://user-images.githubusercontent.com/5359537/155535522-32ba2ae9-fb3d-4ca4-a7b6-5cc2f9f8f68e.png)

In `ActivityLog.xml` i see error message:

```paste below
CreateInstance failed for package [CodeTimePackage]Source: 'mscorlib' 
Description: Не удалось загрузить файл или сборку "Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл. System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл. File name: 'Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) 
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Get Microsoft Visual Studio Community 2019 Version 16.11.7
2. Install CodeTime extension from online repository (Extensions -> Manage Extensions ->Left menu item "Online")
3. Restart Visual Studio

**Expected behavior**
All works without any errors.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2 19042.1526
 - Plugin version v2.6.10

**Comment by TrashBinNp2019** [comment]
Это репозиторий для vscode, а проблема вызвана версией для vs. https://github.com/swdotcom/visualstudio-codetime
