### ISSUE TITLE
Unable to login in vscode

### ISSUE THREAD

**Issue by shubhanus** [swdotcom/swdc-vscode#4]
Installed extension then clicked on bottom right  ⚠️code time that opens a tab in browser and i logged in with google there it is showing dashboard but vscode still ⚠️code time, and on hover it tells click to login.

**Comment by andrewhli** [comment]
Appreciate your note. To help us diagnose the issue, are you using Windows, Mac, or Linux?

**Comment by shubhanus** [comment]
Sorry for not to mentioning.
Env details:
MAC OS MOJAVE 10.14.2
VS-CODE - 1.30.2
Code time - 0.5.56

I have figured out that issue is there with latest(0.5.56) version. i downgraded to 0.5.56 and its logged in, but now issue is, not tracking time properly. it got stuck to 2 min and some 37 keystroke. it is not moving at all.

**Comment by andrewhli** [comment]
Thank you for the details. We're fixing it now and will let you know when it's complete.

**Comment by xavluiz** [comment]
Thank you for the quick reply to the issues you noticed. Our apologies but the app server was getting upgraded during that time and could not respond with the authentication handshake that was required. By the time you downgraded it was up and serving these responses. I've also updated vscode to make this authentication check in a more expedient way to allow your time info to become available without too much delay. the latest vscode update is 0.5.57. Thank you again.

**Comment by shubhanus** [comment]
but what about that time time tracking update its not moving at all

CODE TIME

Today (Sun, Feb 3rd)
--------------------------------------------------------------
     Hours coded today :                                2 min
            90-day avg :                                0 min
  Current session time :                                0 min
              Last KPM :                                 🚀 0

Yesterday (Sat, Feb 2nd)
--------------------------------------------------------------
           Hours coded :                                    0
      Total keystrokes :                                    0
                   KPM :                                    0
   Lines of code added :                                    0
 Lines of code deleted :                                    0
      Characters added :                                    0
    Characters deleted :                                    0

Last week (Sun, Jan 27th - Sat, Feb 2nd)
--------------------------------------------------------------
           Hours coded :                                    0
      Total keystrokes :                                    0
                   KPM :                                    0
   Lines of code added :                                    0
 Lines of code deleted :                                    0
      Characters added :                                    0
    Characters deleted :                                    0

  🎸 Weekly code time by genre
  -----------------------------------------------------------
  No code time by genre available

  🚀 Weekly top commit files
  -----------------------------------------------------------
  No weekly top commit files available

  📂 Weekly top projects
  -----------------------------------------------------------
  No weekly top projects available

  🔥 Weekly code time heatmap
  -----------------------------------------------------------
  No weekly code time heatmap available

90-day avg by day of week
--------------------------------------------------------------
                Sunday :  0 min
                Monday :  0 min
               Tuesday :  0 min
             Wednesday :  0 min
              Thursday :  0 min
                Friday :  0 min
              Saturday :  0 min

All-time (Feb 3rd, 2019 - Feb 3rd, 2019)
--------------------------------------------------------------
           Hours coded :                                 0.03
      Total keystrokes :                                   37
                   KPM :                                18.50
   Lines of code added :                                    5
 Lines of code deleted :                                    1
      Characters added :                                   27
    Characters deleted :                                    3



This is my latest report

**Comment by andrewhli** [comment]
Thanks. Currently testing this piece and will let you know.

**Comment by xavluiz** [comment]
I see, thank you for that update as well. I'm looking at this now, thank you again.

**Comment by xavluiz** [comment]
It looks like our app server caches the previous info for a few minutes so you should notice time updates but not as frequently as it should display. We now have a fix for this and will be updating our app server within the hour and testing. I will send you an update when this is ready and thank you very much for the feedback.

**Comment by xavluiz** [comment]
The server has been restarted and should be serving up new keystroke and time information. Unfortunately we do not keep historical information locally. Our keystrokes and time is kept on the app and is served via the /dashboard  and /session api. Please restart vscode when you get a chance and let us know. We really appreciate your interest in this. Regards.

**Comment by shubhanus** [comment]
Sorry to say that still it's same 2 min and same keystroke.

**Comment by xavluiz** [comment]
Oh, my apologies for not providing that info earlier. The time and keystrokes are updated based on keystroke activity. The plugin periodically sends the app server the number of keystrokes per minute then the app server uses that last keystroke payload to understand your timezone offset to return your coding time information.

**Comment by xavluiz** [comment]
I'll look into what it will take to provide the time and keystroke information without having to wait on keystroke activity as this does seem like latency. My apologies on that and I'll update you later today or tomorrow when that is available. Thank you again.

**Comment by shubhanus** [comment]
Better just give some feature to re auth or logout so that we can clear local cache(if any) and after that again login(so it might get and push fresh data).

**Comment by andrewhli** [comment]
Hi there. We've tested the feature in the following way:

1. Start coding in VS Code (Code Time: 1 min)
2. Open CodeTime Tab (Code Time 1 min)
3. Resume coding in VS Code (Code Time: 10 min)
4. Open new CodeTime Tab - the tab is a static report that refreshes when it's opened again (Code Time: 10 min)

Does the "Hours Coded Today" reflect the correct number after you open a new CodeTime tab? We can also look into making this tab dynamic.

**Comment by shubhanus** [comment]
Hey i don't know all of sudden it synced and started working may be changed to next day that time it logged. thanks for support. and great work i'll try to contribute if i'll get time. But for sure i'll raise a lot feature request after using for a while.

**Comment by andrewhli** [comment]
That's great to hear. Going to close this issue, but we're looking forward to your contributions.

**Comment by andrewhli** [comment]
Hi @shubhanus - we're live on Product Hunt! Would appreciate any support you can give: https://www.producthunt.com/posts/code-time
