### ISSUE TITLE
No Data available

### ISSUE THREAD

**Issue by gptt916** [swdotcom/swdc-vscode#40]
Not sure when it stopped working, but in my dashboard I get the following:

![image](https://user-images.githubusercontent.com/20601623/58564181-7a967a80-81fa-11e9-91c9-f1e9e8a7213e.png)

When I try to log in, I get stuck in a loop in the following order:

Click on code time log in through vscode ->
Open log in page in browser ->
Select github ->
No account found, must install plug in first ->
go back to vscode ->
repeat.

**Comment by brettmstevens7** [comment]
Argh. Not sure what happened. Could you send me a copy of the `session.json` file in your `.software` folder in your home directory?

**Comment by brettmstevens7** [comment]
Hi @gptt916 - can you try now and let me know if you are able to log in with GitHub?

**Comment by gptt916** [comment]
@brettmstevens7 Sorry I have been away on vacation, I just tried it again and I was able to log in via github. Thanks for the quick turnaround!
