### ISSUE TITLE
Login successful but "Getting started" is still displayed

### ISSUE THREAD

**Issue by jer-coding** [swdotcom/swdc-vscode#404]
**Describe the bug**
```paste below
After login to Code Time the extension still displays "Getting started".
If I try to open the dashboard an error is thrown.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

See Gif below

**Expected behavior**
```paste below
"Getting started". disappears after login and the dashboard can be opened.
```

**ACTUAL RESULTS**

```paste below
See Gif below
```

**Screenshots**
 
![CodeTime-Bug](https://user-images.githubusercontent.com/18305141/160397974-e810548a-6de1-41d6-bb2e-4c529540690a.gif)

**Desktop (please complete the following information):**

 - OS: Win10
 - Code Time v2.6.29

**Additional context**
```paste below

```

**Comment by AKmoex** [comment]
How did you solve it? I had the same problem
