### ISSUE TITLE
Last Week's Stats showing the wrong results

### ISSUE THREAD

**Issue by webdevsumit** [swdotcom/swdc-vscode#408]
**Describe the bug**
```
Last Week's Stats showed the wrong results
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
I don't know how to reproduce that, but I still get the wrong values.

On 26th May 2022, I worked for about 11 hours. But for the same week, I got total hours even less than 5 hours.
I am sharing two screenshots.

Screenshot 1

![image](https://user-images.githubusercontent.com/51439478/170988446-ee6deb5d-46be-4e2c-a6ec-c7431f10d3ab.png)

Screenshot 2

![image](https://user-images.githubusercontent.com/51439478/170989300-a793ff44-140d-42e7-ba01-9ae7321d6c46.png)

**Expected behavior**
It should show at least more than 11 hours

**Comment by bjacobson26** [comment]
should be resolved in newest versions
