### ISSUE TITLE
Always auto open itunes in MacBook

### ISSUE THREAD

**Issue by liupy525** [swdotcom/swdc-vscode#41]
When I upgrade codeTime extension in VSCode to 0.16.5, iTunes was always auto opened. After I forbid extensions one by one, I found it depends on codeTime. Please check out it, thanks.

**Comment by andrewhli** [comment]
Hi there. Apologies for this issue. We've spent the weekend fixing it, and once we've fully validated the fix, I'll let you know

**Comment by andrewhli** [comment]
Hi there. We've fixed this issue on Code Time v0.16.10, and we really appreciate that you've let us know about it. We noticed iTunes auto-opening as well on v0.16.5 and all of us on the team have validated that it no longer happens on v0.16.10. Could you upgrade to this version and let us know how else we can help? Thanks!

**Comment by liupy525** [comment]
Oh, yes, I have tried v0.16.10, it's OK!
Thank for your fixing!
