### ISSUE TITLE
After Install the code time extension showing Blank page and also it's showing blank screen on extension setting

### ISSUE THREAD

**Issue by Santosh-Baliarsingh** [swdotcom/swdc-vscode#411]
**Describe the bug**
**After installation , the extension shows a blank screen and when click the extension setting it's Showing message 'no settings Found'**
![Screenshot 2022-06-08 223249](https://user-images.githubusercontent.com/88627642/172677051-caa42434-f2e7-482d-9c8f-bbb0eecb3880.png)
![Screenshot 2022-06-08 223435](https://user-images.githubusercontent.com/88627642/172677062-9aaa8f1d-daf2-44ed-8604-9ccc2ee3ff70.png)
```paste below

```
**ISSUE TYPE**
- Bug Report

**Comment by rik72c** [comment]
Code Time used to work for a few weeks but now I, too, got this same problem out of no where.

I tried remove everything in "C:\Users\[NAME]\AppData\Roaming\Code\Service Worker" which solved problems in various extentions, but still doesn't work with Code Time.

**Comment by MikeJerred** [comment]
Same here, extension just doesn't work at all anymore.

**Comment by salimelawad** [comment]
I am facing this same issue. Is there a known solution to this?
