### ISSUE TITLE
Today’s Stat’s always show Zero minutes

### ISSUE THREAD

**Issue by Rivera-Emmanuel** [swdotcom/swdc-vscode#418]
**Describe the bug**
```paste below
“Today’s”  Code Time and Active Code Time show 0m. It updates some time on the following day. Time used to update in real time.
Issue starting occurring around August 2nd 2022. Not recoverable by rebooting or restarting VS Code application.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Go to ’Stats'
2. Click on ‘Dashboard'
3. See error

**Expected behavior**
```paste below
Time used to update in real time.
```

**ACTUAL RESULTS**

```paste below

Code Time | 0m | ⬆ | 0% vs 90 day avg (0m)
-- | -- | -- | --
Active Code Time | 0m | ⬆ | 0% vs 90 day avg (0m)

Note: at the time of these results, I’ve been programming for over 8 hours actively.

```

**Screenshots**

**!SHOULD SHOW ABOUT 8 HOURS OF ACTIVE CODE TIME!**

![image](https://user-images.githubusercontent.com/75558288/182978519-cd2a2418-0d02-49f2-a074-976a0cc6dc25.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 12.5
 - Plugin version Code Time v2.6.33
 - VS Code Version: 1.70.0 (Universal)

**Additional context**
```paste below

```

**Comment by FireBreather65** [comment]
I'm having the same issue. My OS is Windows.

**Comment by yongen9696** [comment]
the same bug happens over here even tried downgrading the extension version.

**Comment by MohanSaiManthri** [comment]
Same here it stays in always zero

**Comment by mmclead** [comment]
Hi everyone.  Sorry about that.     we had a misconfiguration.   I've adjusted it now and the stats are back.   The correct times will show up on the dashboard and in your status bar at the bottom.
