### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by odaga** [swdotcom/swdc-vscode#419]
- Issue Type: `Performance`
- Extension Name: `swdc-vscode`
- Extension Version: `2.6.33`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/HQ/AppData/Local/Temp/softwaredotcom.swdc-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bjacobson26** [comment]
should be resolved in new versions
