### ISSUE TITLE
I can't collapse blocks of code when extension enabled

### ISSUE THREAD

**Issue by oleh-26-01** [swdotcom/swdc-vscode#421]
I can't collapse blocks of code when extension is enabled. And I can collapse while the extension is disabled.

**Comment by xavluiz** [comment]
Hi @oleh-26-01,
I've tested collapsing and expanding blocks of code such as ruby and javascript and it works for me. If you have more information as to how we can reproduce this we can look more into this, thank you.

**Comment by oleh-26-01** [comment]
The problem was not in this extension, there is no such bug.
