### ISSUE TITLE
Not getting the right date for yesterday and last week

### ISSUE THREAD

**Issue by bilalzhd** [swdotcom/swdc-vscode#424]
It is not already on GitHub.

**Describe the bug**

I am not getting the right date for yesterday's stats, the date for today's stats is right, but when I go to dashboard the yesterday's stats is something 16 July, and also last week's stats = July Month. 

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
<!--- Describe exactly how to reproduce the problem -->

1. Go to 'Extension Code Time'
2. Click on 'Dashboard'
3. Scroll down to 'Yesterday's Stats
4. See error i.e. yesterday's date would not be correct.

<!--- HINT: You can paste gist.github.com links for larger files -->

**Expected behavior**
A clear and concise description of what you expected to happen.
```paste below
I expected it to be right e.g if today is 29 Oct then on yesterday's stats it should be 28th October but I am getting July 16 something.
```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**
![code time bug](https://user-images.githubusercontent.com/88459741/198817001-43e85caf-6032-4808-a2e2-9cee8f91f14e.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by mmclead** [comment]
Hi. Sorry for this issue.   The date's being shown are definitely incorrect.  The data should be right now.  

We'll get this updated and fixed right away.   Thanks for alerting us @bilalzhd

**Comment by mmclead** [comment]
This has been fixed.  Thanks again
