### ISSUE TITLE
Button isn't working

### ISSUE THREAD

**Issue by ricemashi** [swdotcom/swdc-vscode#428]
**Describe the bug**
```paste below
I tried clicking on the "create an organization" button but it doesnt seem to respond. 
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Go to 'Codetime's Sidebar Application'
2. Click on 'Create an Organization'

**Expected behavior**
```paste below
Expected the button to open a link to the dashboard or create an organization on a new webview
```

**ACTUAL RESULTS**

```paste below
It doesn't respond when I click my button.
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin version: v2.6.35

**Comment by xavluiz** [comment]
Hi @ricemashi 
Apologies for the late reply. We've fixed this issue in v2.6.40.

Thank you for the update on this.
