### ISSUE TITLE
Web dashboard: Duplicate entries in feed

### ISSUE THREAD

**Issue by gsabater** [swdotcom/swdc-vscode#43]
Hello,

I have detected a bug where when I click on feed and then on calendar, returning to feed duplicates the cards.

This happens each time I do the process.
See attached:

![bug](https://user-images.githubusercontent.com/4948172/60253777-00c2e100-98cd-11e9-8988-883d1f520a8e.png)

**Comment by andrewhli** [comment]
Hi Gaspar. Thanks for letting us know. We recently implemented browser caching which is likely causing this issue. Today, we'll work to make sure the browser cache does not result in duplicates.
