### ISSUE TITLE
Extension was enabled but didn't collect data and now shows nothing in VSCode

### ISSUE THREAD

**Issue by ThorsAngerVaNeT** [swdotcom/swdc-vscode#430]
**Describe the bug**
Starting 2022-11-26 till now I have 0 minutes of coding based on the dashboard at the website. Extension in VSCode seems not working and has infinite loading animation. I have disabled/enabled and even reinstalled the extension. Nothing helps.

**ISSUE TYPE**
- Bug Report

**Screenshots**
![image](https://user-images.githubusercontent.com/17920285/205441799-d41bd5c8-89d3-4ad0-935d-c5b588f8f11b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin version v2.6.35

**Comment by KhuntJenish** [comment]
![Capture](https://user-images.githubusercontent.com/83546046/211469494-47940ca8-1e79-4f02-8ff6-099ccddc14d1.PNG)


I also Facing same problem on my Vs Code

**Comment by mosope02** [comment]
I have the same issue
