### ISSUE TITLE
Installs Settings in ~/.software

### ISSUE THREAD

**Issue by ProfessorManhattan** [swdotcom/swdc-vscode#438]
Hey, after installing this, a folder appeared at `$HOME/.software` with a few different files. Would it be possible to move this data to the User folder (i.e. `$HOME/.config/Code/User`)? Preferrably, we should follow the XDG spec as well as fallback to the actual VSCode instance User settings folder. For instance, with an install via Flatpak, the User folder is at `/home/parallels/.var/app/com.visualstudio.code/config/Code/User`. But if you need to store settings outside of the VSCode User folder, then I propose that we follow the XDG spec so people's `$HOME` don't get too crowded with all these dot files.

**Comment by bjacobson26** [comment]
We've updated this - we don't install anything in your home directory anymore.
