### ISSUE TITLE
The calendar issue in https://app.software.com/calendar/codetime

### ISSUE THREAD

**Issue by Joel-hanson** [swdotcom/swdc-vscode#44]
On clicking the `suggested code time` shows us this issue, but my google account is linked to the app.

![Screenshot 2019-06-27 at 2 46 01 PM](https://user-images.githubusercontent.com/17215044/60253998-bb151100-98ea-11e9-9e6c-b46ff8a5c1d2.png)

![Screenshot 2019-06-27 at 2 48 54 PM](https://user-images.githubusercontent.com/17215044/60254005-be100180-98ea-11e9-921d-0a992e1e0563.png)

**Comment by andrewhli** [comment]
Hi Joel. Sorry that the app is causing this issue. We'll debug the problem today.

**Comment by andrewhli** [comment]
Hi @Joel-hanson - We fixed this problem a couple weeks ago, but I'm only following up now. Apologies! Please let us know if this continues to be a problem

**Comment by Joel-hanson** [comment]
Thanks @andrewhli
