### ISSUE TITLE
not recording time

### ISSUE THREAD

**Issue by BakerAlblam** [swdotcom/swdc-vscode#441]
**Describe the bug**
```paste below

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by xavluiz** [comment]
Hi @BakerAlblam,
I'm unable to see an error description in the issue. Do you have the latest Code Time version? We're currently on v2.6.43. Let us know how we can help, thanks!
