### ISSUE TITLE
code time not working

### ISSUE THREAD

**Issue by badaovz** [swdotcom/swdc-vscode#442]
## code time not working

**Comment by xavluiz** [comment]
Hi @badaovz,
What error are you currently experiencing? v2.6.43 looks like its working for us but if there's something you've found an issue with us please let us know with a description of how to reproduce the issue, thanks!

**Comment by vistar** [comment]
Extension doesn't worked for me since December 12th.
When you click on the extension button, there is an endless update, and nothing else.

Extension: v 2.6.44
VS Code: 1.75.0
on Linux

**Comment by glawon** [comment]
I'm having the same problem. But it worked till February 2nd. 
I'm using Ubuntu.

**Comment by TeqGin** [comment]
For me, it take a long time to load getting started and unable to register account. 
After click Register your account button, nothing happens.

**Comment by srikant-marvel** [comment]
### Code time is broken. Version 2.6.47 
---

https://user-images.githubusercontent.com/52560067/221405097-42a06542-e10f-475e-bd53-be032bb7e344.mp4

**Comment by daidaiworm** [comment]
vscode 1.75.1
Code Time 2.6.47

same issue as @srikant-marvel

**Comment by CaptainStabs** [comment]
Still broken.
