### ISSUE TITLE
Sem conexão a conta

### ISSUE THREAD

**Issue by lucaphill** [swdotcom/swdc-vscode#449]
**Describe the bug**
```
Quando eu clico para criar uma conta nada acontece, caso eu clique 
para conectar aparece um contorno laranja, mas nada acontece.

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Go to 'code timo na barra de tarefas'
2. Click on 'conectar a conta'

**Expected behavior**
```
imagino que deveria aparecer uma janela para se conectar a conta. 

```

**Comment by xavluiz** [comment]
We apologize for the issue. We have an open pull request that will resolve later today, thank you.

**Comment by Gabriel-Fellipe** [comment]
Mutio obrigado pela atenção, aparentemente o problema foi resolvido. Consegui conectar na minha conta.
