### ISSUE TITLE
Time Tracking

### ISSUE THREAD

**Issue by kushpvo** [swdotcom/swdc-vscode#45]
Does it track even when VSCode is Open in background or just when VSCode window is active?

I'm asking this because I generally keep VSCode open even when I'm working on non-code work on my laptop - need to know if it will affect or not

**Comment by andrewhli** [comment]
Hi @kushpvo. This is a great question that users frequently ask us. 

The answer is "No," keeping the editor open should not skew your metrics. You do not need to close VS Code to ensure that Code Time metrics are correct. 

The timer starts when you start typing. It stops after 15 minutes without typing or opening/closing files in the editor. We then truncate the last 15 minutes of inactivity from the data. 

Definitely let us know if you have more questions!

**Comment by andrewhli** [comment]
@kushpvo - Could you send your email address to andrew@software.com? I'd like to invite you to our private user community.

**Comment by kushpvo** [comment]
> @kushpvo - Could you send your email address to [andrew@software.com](mailto:andrew@software.com)? I'd like to invite you to our private user community.

Thanks a lot for the explanation! The implementation seems perfect! 
Here's my email : kushpvo@gmail.com
