### ISSUE TITLE
An error occurred while loading view: codetime.webView

### ISSUE THREAD

**Issue by developernajib** [swdotcom/swdc-vscode#456]
**Describe the bug**
```paste below
An error occurred while loading view: codetime.webView when I am opening my vscode codetime extension. Showing only the error on the black area nothing else
```
**ISSUE TYPE**
- Bug Report

**Expected behavior**
```paste below
Show the codetime extension dashboard so that I can login into my account
```

**ACTUAL RESULTS**

```paste below
Only black area and this text "An error occurred while loading view: codetime.webView"
```

**Screenshots**
<a href="https://i.ibb.co/xGS3MVN/Screenshot-1.jpg" target="_blank">
<img src="https://i.ibb.co/xGS3MVN/Screenshot-1.jpg" alt="error" />
</a>

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by CaptainStabs** [comment]
Same issue I'm having in #453 

Logs for the error:
https://github.com/swdotcom/swdc-vscode/issues/453#issuecomment-1465328048

**Comment by developernajib** [comment]
Issue resolved, thanks
