### ISSUE TITLE
pop-up tab "Music Time Dashboard"

### ISSUE THREAD

**Issue by rmb-dev** [swdotcom/swdc-vscode#46]
I have this empty pop-up tab "Music Time Dashboard" every time I launch the VS code editor.
How to get rid of it?
![issue](https://user-images.githubusercontent.com/22654796/61567388-fc32b800-aa87-11e9-8be8-ceb7a8add449.png)

**Comment by andrewhli** [comment]
This is a bug related to a new feature we're working on. We sincerely apologize for the frustration here. Going to work with the team to fix this one right now and update you of our progress.

**Comment by andrewhli** [comment]
Hi @rmb-dev. We just pushed v1.1.18 to the VS Code marketplace: https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode. This should prevent the Music Time Dashboard from appearing, but definitely let us know if it continues or if you see anything else.

**Comment by rmb-dev** [comment]
Wow, that was fast!
Thanks, it's fixed now.

**Comment by andrewhli** [comment]
@rmb-dev - Could you send your email address to andrew@software.com? I'd like to invite you to our private user community.
