### ISSUE TITLE
Doesn't record code time when not connected to internet

### ISSUE THREAD

**Issue by ifedolapoomoniyi** [swdotcom/swdc-vscode#463]
**Describe the bug**
```paste below

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by mmclead** [comment]
that's due to the way the extension works.    We track activity metadata and aggregate them inside our system, apply some ML and then push back the results via web sockets.    

It should keep track of your activity while offline and then refresh that data once you do connect.

**Comment by ifedolapoomoniyi** [comment]
I searched all over and I couldn't find someone explaining what exactly was going on. Thank you very much
