### ISSUE TITLE
I want to add ot only flow time but also active time to Google Calendar on Integration.

### ISSUE THREAD

**Issue by Yuhi-Aoki** [swdotcom/swdc-vscode#471]
##### SUMMARY

Thank you for developing a wonderful application. I am happy with flow mode!

###### My opinion
When using Google calendar integration, we can add flow time to our Google calendar through this integration.  But, Active Time cannot be added to my Google Calendar.

**Is it necessary to set preferences?**

If not, I would like to develop the functional that **this integration add active time to Google Calendar**.

If you want this feature, please reply with 👍.

I don't have any of this application knowledge, so I need help from those who do.

##### ISSUE TYPE
- Feature Request

**Comment by mmclead** [comment]
That's a good idea.    This would be implemented on our backend app, and we'll this suggestion to our list.

However, you can see your Active Code Time on a calendar view at https://app.software.com/calendar

Does this do enough of what you are looking for, or does having the Active Code Time event on your actual calendar give some specific value that the other view does not?

p.s.
On that calendar page we also look at the timing patterns of coding sessions to recommend "Suggested Code Time" that will reserve time in your calendar proactively.
