### ISSUE TITLE
Git Push Hang

### ISSUE THREAD

**Issue by pavlovcik** [swdotcom/swdc-vscode#472]
Hey guys, I have a repo with two remotes. None have `origin` as the name of the remote. 

When I push, there is a crazy lag (~30 seconds) 

I checked the logs and the extension was spamming 
```
git config --get remote.origin.url
```

This didn't exist because I had no remote named `origin`

I think it would be wise instead to check the current remotes, and then get the URLs from there. 

Name: Code Time
Id: softwaredotcom.swdc-vscode
Description: Code Time is an open source plugin that provides programming metrics right in Visual Studio Code.
Version: 2.7.4
Publisher: softwaredotcom
VS Marketplace Link: https://marketplace.cursorapi.com/items?itemName=softwaredotcom.swdc-vscode

**Comment by mmclead** [comment]
Thanks for the note on this.  looking at this now.
