### ISSUE TITLE
Protected code time duplicate itself in calendar view 

### ISSUE THREAD

**Issue by elkeis** [swdotcom/swdc-vscode#478]
**After protecting code time window  it start duplicate itself in calendar view**

**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

0. Connect to google calendar
1. Go to calendar view on website
2. Click on code time suggestion e.g. on Wednesday
3. Protect only for selected slot/day
4. See code-window protected on Monday also.
4.1 By clicking on Monday protected time slot see wrong date.

**Expected behavior**

Expected to see same picture as in a calendar.
![Screenshot 2024-01-25 at 15 09 34](https://github.com/swdotcom/swdc-vscode/assets/4289257/4dbf8705-be7b-42e3-8ebf-a2814e799e1d)

**ACTUAL RESULTS**
Duplicates on calendar view
<img width="770" alt="Screenshot 2024-01-25 at 15 07 18" src="https://github.com/swdotcom/swdc-vscode/assets/4289257/f5cfe367-b431-4638-99ca-ffdf3932e3cb">

**Comment by mmclead** [comment]
Thank you for the bug report.   Looking into this

**Comment by elkeis** [comment]
@mmclead , I took a look today, the issue is gone. But after I clicked on today's protection window it got duplicated again with Monday one.

So when I click on Monday protected code time window, popup says it's Friday one.

<img width="834" alt="Screenshot 2024-01-26 at 15 28 52" src="https://github.com/swdotcom/swdc-vscode/assets/4289257/c3bc8863-99b7-4bd5-baf7-2002917ab71b">
