### ISSUE TITLE
Status bar rocket ship question. 

### ISSUE THREAD

**Issue by franck-noahk** [swdotcom/swdc-vscode#48]
I was wondering if the Rocket ship that appears at the bottom of vs code in the status bar means anything. I have seen it sometimes and other times it isn't there. I couldn't really find any FAQ or info about it. Sorry its not really a issue and more of a question.

**Comment by andrewhli** [comment]
Hi Noah. This is a great question! We show the rocket ship when your time code today exceeds your daily code time's 90-day average. Let us know if you have any recommendations or any other questions.
