### ISSUE TITLE
 Cannot read properties of undefined (reading 'work_hours')

### ISSUE THREAD

**Issue by nick-rbzk** [swdotcom/swdc-vscode#481]
Activation
Activated by onStartupFinished event: 13ms

Uncaught Errors (1)
 Cannot read properties of undefined (reading 'work_hours')

**Comment by mmclead** [comment]
Thanks for the bug report.  Looking in to it.

**Comment by xavluiz** [comment]
Hi @nick-rbzk,
Apologies for the delay in the reply. We've fixed this issue and will be available in the following version: swdc-vscode@2.7.8. Thank you.
