### ISSUE TITLE
Cannot login with the Remote-SSH extension

### ISSUE THREAD

**Issue by bogdan-calapod** [swdotcom/swdc-vscode#49]
Hello,

First of all, thanks a lot for this extension! The insights are really useful :D

I have noticed that this extension doesn't really play well with the [VSCode Remote SSH Development](https://code.visualstudio.com/docs/remote/ssh#_managing-extensions) extension.

*Expected behavior*

The extension installs as an UI extension, allowing me to log in from the `Ctrl + Shift + P` Log In option.

*Actual behavior*

The extension installs as a Workspace extension. Tracking works, but the login option does nothing.

*Current workaround*

Following the steps [in the official Remote documentation](https://code.visualstudio.com/docs/remote/ssh#_managing-extensions) to force the extension to be UI/Local fixes the issue. 

This basically means adding this to your `settings.json`:
```json
    "remote.extensionKind": {
        "softwaredotcom.swdc-vscode": "ui"
    }
```

If I can help with a PR that fixes this or anything else, let me know :)

**Comment by brettmstevens7** [comment]
Thanks for sharing! We added that snippet to the `package.json` in the latest version (1.1.22). Can you try this out in your environment and let us know if it works for you?
