### ISSUE TITLE
Does it count work time outside the timetable stablished 

### ISSUE THREAD

**Issue by sultanos** [swdotcom/swdc-vscode#495]
##### SUMMARY

```paste below
Does it count work outside the time table created
```

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

```paste below
I guess that for payers this feature should be off all the time , but many times we do extra hours and i am no sure if they get counted by default, it would be great to color them and sum them in another color
```

**Comment by mmclead** [comment]
Hello.  Yes it will count the hours outside the working schedule.    We use that let you know how much time you are putting in outside your normal working hours so you can keep an eye on that balance.
