### ISSUE TITLE
does not update active code time

### ISSUE THREAD

**Issue by thanhlucifer** [swdotcom/swdc-vscode#497]
I code from 9am to 12pm but my active code time to day is 0m, I don't understand why this is so

**Comment by bjacobson26** [comment]
Hi @thanhlucifer, 

What version of the plugin are you using? 

The timer in the app is updated every 5 minutes. restarting vscode may resolve the issue you're seeing. 

Does your code time look correct on the web app dashboard?  https://app.software.com/code_time

**Comment by mmclead** [comment]
Hello.  We were having some processing issues yesterday that delayed updating the CodeTime.   thats been corrected now and your data should be up to date.   We did capture all the timing data, so you won't have lost any.  

Thanks for you patience on this.  

Mason
