### ISSUE TITLE
[Discussion] Track time spent collaborating with other developers

### ISSUE THREAD

**Issue by lostintangent** [swdotcom/swdc-vscode#5]
I’m really enjoying this extension, and I was curious whether it would make sense to track the time that developers spend collaborating via [Live Share](aka.ms), since that provides another dimension to their time spent coding. Live Share provides an [API](nodejs.com/vsls) that would allow you to detect when a developer is in a collaboration session, and could be a potentially interesting integration.

**Comment by brettmstevens7** [comment]
Hey Jonathan, thanks for the suggestion! We’ll do some research into how we could implement this idea.

**Comment by lostintangent** [comment]
@brettmstevens7 Sounds good! Let me know if there’s anything you’d need from the Live Share team in order to make this happen 👍

**Comment by lostintangent** [comment]
In addition to tracking the time spent collaborating, I also noticed that if you join someone else’s collaboration session, it reports the project as “Share (Workspace)”, as opposed to the actual project name. It would be great if the correct project name was reported, regardless if you were working alone, or hosting/joining a collaboration session.

**Comment by brettmstevens7** [comment]
Thanks for the feedback, we’ll work on getting the correct project names in.

**Comment by brettmstevens7** [comment]
Hey @lostintangent - we're now tracking the actual project name instead of “Visual Studio Live Share (Workspace)” when you join someone else's collaboration session. Thanks for pointing that out!
