### ISSUE TITLE
Please have a setting to stop console spam

### ISSUE THREAD

**Issue by tecosaur** [swdotcom/swdc-vscode#50]
I use this extension while developing other extensions, and unfortunately, due to how prolific this extension is at logging it makes it hard to find important log messages.

![image](https://user-images.githubusercontent.com/20903656/62297597-1fa42c80-b4a4-11e9-97a5-533d9161049f.png)

Please add a setting to disable this, if it's needed at all.

Thanks.

**Comment by brettmstevens7** [comment]
Hi @tecosaur, this feature was just added in v1.1.22. Thanks for the suggestion.

<img width="773" alt="Screen Shot 2019-08-05 at 1 03 15 PM" src="https://user-images.githubusercontent.com/27828739/62491731-9598e400-b781-11e9-9b19-968ac33bb8dc.png">
