### ISSUE TITLE
Still billed even after cancelling subscription / No contact form

### ISSUE THREAD

**Issue by eguenou** [swdotcom/swdc-vscode#502]
Hello,
I am still billed even after cancelling my subscription. There is no contact form on the website.
To which email address should I write?
Thanks

**Comment by bjacobson26** [comment]
Hi @eguenou - your subscription should now be cancelled and refunded. 

You can contact us through the Help option on the web app if there are further issues. 

Thank you.

**Comment by eguenou** [comment]
Hello,
The 'Help' button is not opening any page. It acts like a fake button.
That is why I contacted you directly here.
Can you confirm that the claim is taken into account by someone please?
Or can you give the URL the help button should open please?
Thanks for answering.

**Comment by bjacobson26** [comment]
@eguenou The Help button opens a form on the web app to contact us: 
<img width="440" alt="image" src="https://github.com/swdotcom/swdc-vscode/assets/9271952/4fbe18be-b0d0-4ee8-9ec4-ce39d6eebb48">

It is possible that the browser you are using is blocking the javascript from executing. This has been tested on the latest versions of Chrome, Firefox, and Safari. 

Opening an issue here or contacting us at support@software.com are alternative ways to get in touch if other folks have this issue.
