### ISSUE TITLE
Please enter a valid work email

### ISSUE THREAD

**Issue by olafswan** [swdotcom/swdc-vscode#509]
**Not supporting email address like john.doe@gmail.com**

As suggested, after installation, I tried to register, but I initially attempted it on the software.com website. 

After signing in using 'Sign in with Google', I was stuck on the 'Set up your organization' modal because the email input returned the error: `'Please enter a valid work email.'` 
I almost gave up and uninstalled the VSCode extension. 

![code-time](https://github.com/user-attachments/assets/61b30d93-edc4-449a-a91c-4b9b84db1f22)

The only fix was to register using the VSCode registration button.

**Fix suggestions**
Allow to skip the create organization form.

**Comment by bjacobson26** [comment]
Hi @olafswan - thanks for bringing this issue up. 

If you sign up by going directly to software.com, it'll drop you into onboarding for our [platform product](https://www.software.com/product) for organizations. 

As you found, the only way to register your CodeTime account is to do it is through the VSCode plugin's "Register your account" button:
<img width="649" alt="image" src="https://github.com/user-attachments/assets/d0953821-432b-4109-a5e9-7e6076d14a09">

That being said, it is quite frustrating not being able to skip that create organization form. Will look into allowing skipping that. Thanks for the suggestion!
