### ISSUE TITLE
My Yesterday's code time is not showing 

### ISSUE THREAD

**Issue by AliSherNadeem** [swdotcom/swdc-vscode#511]
Hi Code Time Support Team,

I’ve noticed an issue with the Code Time extension in VS Code. My coding activity from yesterday isn’t showing up. Yesterday, my total coding time for the day was displayed correctly (2hrs 53 min) the extension, but it wasn’t added to my weekly total after 12 am., and it hasn't been added to my total weekly code time as of today. Could you please assist in resolving this issue?

Thanks for your help!

**Comment by mroungou** [comment]
I have also been having the same problem. Weekly stats haven't updated since Wednesday.

**Comment by bjacobson26** [comment]
Hi @AliSherNadeem and @mroungou - we had a bug that was just resolved. Your code time should be accurate now. Let us know if there is still an issue. Thank you!
