### ISSUE TITLE
For past two days the code time and the active code time is not displaying in the graph

### ISSUE THREAD

**Issue by Joyel2003** [swdotcom/swdc-vscode#512]
![Screenshot 2024-10-26 093542](https://github.com/user-attachments/assets/3a09e891-a18f-4341-872c-2d1fbb2ec8a0)

**Describe the bug**
```For past two days the code time and the active code time is not displaying in the graph
 the graph is showing as 0 hrs
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by bjacobson26** [comment]
Thanks for the bug report, we're looking into it.

**Comment by bjacobson26** [comment]
Hi @Joyel2003 - the problem should be resolved now. Let us know if there is still an issue. Thank you!

**Comment by Joyel2003** [comment]
Thanks for the information and for the problem solving
