### ISSUE TITLE
code time and active code time is not working today

### ISSUE THREAD

**Issue by Joyel2003** [swdotcom/swdc-vscode#514]
**Describe the bug**
code time and active code time is not working today

```
**ISSUE TYPE**
code time and active code time is not working today

**Steps to reproduce**
<!--- Describe exactly how to reproduce the problem -->

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

<!--- HINT: You can paste gist.github.com links for larger files -->

**Expected behavior**
A clear and concise description of what you expected to happen.
```paste below

```

**ACTUAL RESULTS**

```paste below

```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by bjacobson26** [comment]
Hi @Joyel2003 - are you still experiencing issues? Thank you

**Comment by bjacobson26** [comment]
should be resolved in latest update.
