### ISSUE TITLE
code time isn't working for last 3 days.

### ISSUE THREAD

**Issue by farnazrhr** [swdotcom/swdc-vscode#516]
**Describe the bug**
```
In my VScode, code time hasn't working for 3 days, and I tried to delete and reinstall it again, but it doesn't work.
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
even in the sidebar, it doesn't show the dashboard.

**Expected behavior**
```
working correctly
```

**Screenshots**
![code-time-bug](https://github.com/user-attachments/assets/a4f0541d-97ba-4867-a04a-27394c846954)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Plugin version: Code Time v2.8.2

**Comment by thefaizaankhan** [comment]
Yes the issue persists. It is not resolving.

**Comment by farnazrhr** [comment]
> Hi @farnazrhr - we've been unable to reproduce the issue. are you still experiencing issues?

Yes, I still have this issue, and it's not solved. for now, I'm using the previous version, and it's working.

**Comment by farnazrhr** [comment]
> > Hi @farnazrhr - we've been unable to reproduce the issue. are you still experiencing issues?
> 
> Yes, I still have this issue, and it's not solved. for now, I'm using the previous version, and it's working.

update: in the last version 2.8.3 it's solved thanks.

**Comment by thefaizaankhan** [comment]
Working fine now. Great!! Thank you so much.

**Comment by thefaizaankhan** [comment]
> Hi @farnazrhr - we've been unable to reproduce the issue. are you still experiencing issues?
@bjacobson26  Thank you so much!
