### ISSUE TITLE
Web Dashboard not opening from 

### ISSUE THREAD

**Issue by subz390** [swdotcom/swdc-vscode#53]
Opening the Web Dashboard has stopped working from within VSCode (see screengrab for details)
```
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
```
![stopped working](https://user-images.githubusercontent.com/11546815/63434532-342d7200-c41d-11e9-87cf-cd10fd2c6c83.png)

And on top of that, finding the URL of the Web Dashboard... why is it such a secret?  I never noticed before, and didn't even bookmark the URL as the above link worked just fine.  But since it's not working I wanted to check up on my stats and am shocked to see that you've not printed the URL in any of the prominent places where it aught to be advertised as connected to the plugin as a service.  I don't know about anyone else but I think that's wrong.
[https://app.software.com/](https://app.software.com/)

**Comment by thedelk** [comment]
@subz390 I had to check to make sure I didn't submit this in my sleep, because this is the exact experience I've had - right down to trying to find the URL and finally giving up.

**Comment by brettmstevens7** [comment]
@subz390 and @thedelk - thanks for bringing this to our attention! Looks like we had a bug with opening links on Windows NT. We've updated our plugin to use the `open` NPM. This should work in v1.1.25 which was just pushed to the marketplace. We've also added a link to the web app in the README.
