### ISSUE TITLE
Project file open metric

### ISSUE THREAD

**Issue by subz390** [swdotcom/swdc-vscode#54]
Please excuse if this has already been suggested / requested, I would like a metric that records project file open time.  It's kinda like this, when I start work on a project I open the project folder in VSCode.  When it's the end of the morning session and I have lunch I close VSCode.  I then reopen the project again for the afternoon.  How much actual typing I do in the project is variable.  Sometimes I'm doing research, or studying theory related to the project.   In which case I'm still working on the project, just not much typing into it.  So I feel whilst the current sytem of recording activity by the amount of typing into the project is good to have, I do feel that the overall period of activity on a project can be measured by how long the project is open.  And before people start jumping down my throat about this and that - it's an option.  If you don't like it disable it, now settle down.  For me, I've just been researching for my current project for the past hour and swdc says I've only worked on it for 2 min.  It feels disapointing and like the rest of my stats are unfair too.

**Comment by brettmstevens7** [comment]
Great idea to capture wall time. We'll add it to the roadmap.
