### ISSUE TITLE
Antimalware Service Executable high CPU usage when Ctrl+T (Show All Symbols)

### ISSUE THREAD

**Issue by liyuhang1997** [swdotcom/swdc-vscode#55]
- VSCode Version: 1.38.1
- OS Version: Windows 10 v1903 (OS Build 18362.356)

Steps to Reproduce:

1. Ctrl + T
2. Antimalware Service Executable high CPU usage, the computer becomes very stunned.

Does this issue occur when `Code Time for Visual Studio Code` extensions are disabled?: No

**Comment by bjacobson26** [comment]
Unable to reproduce. Please update to latest CodeTime v2.3.2 and reopen this issue if the problem persists. Thank you!
