### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by anirban94chakraborty** [swdotcom/swdc-vscode#56]
- Issue Type: `Performance`
- Extension Name: `swdc-vscode`
- Extension Version: `1.1.29`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

(https://github.com/swdotcom/swdc-vscode/files/3620672/softwaredotcom.swdc-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by EthanZeigler** [comment]
Can confirm for macOS 10.14.6, same VScode and extension version

**Comment by dpDesignz** [comment]
Can confirm for `Windows 10 Pro 2004 19041.172 x64` (`Windows_NT x64 10.0.19041`), VSCode `1.43.2`, extension version `2.1.47`. I already had to disable to new music app due to performance issues. 😢

**Comment by brettmstevens7** [comment]
Hi @dpDesignz - if you could record and send us a cpuprofile, that would help us get to the root-cause of your issue. Here are the steps to follow: https://github.com/microsoft/vscode/wiki/Performance-Issues

We've made a few performance improvements in the past few weeks and re-tested using Code Time and Code Time + Music Time, but let me know if any issues persist.

**Comment by dpDesignz** [comment]
> 
> 
> Hi @dpDesignz - if you could record and send us a cpuprofile, that would help us get to the root-cause of your issue. Here are the steps to follow: https://github.com/microsoft/vscode/wiki/Performance-Issues
> 
> We've made a few performance improvements in the past few weeks and re-tested using Code Time and Code Time + Music Time, but let me know if any issues persist.

I've just re-enabled it to test again. Will see how it goes.

**Comment by bjacobson26** [comment]
Hi everyone - we're keeping our eye on this one. We have made many updates in the past few months that should improve performance. If the problem persists in CodeTime v2.3.2 or greater, please re-open this issue. Closing it for now. Thank you!
