### ISSUE TITLE
Total code time wrong numbers

### ISSUE THREAD

**Issue by prydda** [swdotcom/swdc-vscode#58]
So the .md file is now showing half of my actual code time.. 
I'd over 300 hours in all time. Now it's showing 139 hours..

**Comment by prydda** [comment]
@brettmstevens7 @xavluiz

**Comment by bjacobson26** [comment]
Hi @prydda - hopefully your issue has been resolved with all the updates that have been pushed over the past year. I'm going to close this issue for now, but if you are still experiencing problems please re-open it and let us know what is going on. Thank you!
