### ISSUE TITLE
my code time Disappeared

### ISSUE THREAD

**Issue by Saafo** [swdotcom/swdc-vscode#59]
I began to use a new device today, I downloaded VS Code and installed the Code Time, but I forgot to login. At night I finally recognized that, I've already worked for 4.9hrs in VS Code, and I login by my Github account. But after I login, the 4.9hrs turned to 0min! It seemed that you hadn't design uploading the already-exsisted data feature after login?  
My device is MacBook.

**Comment by delliotthart** [comment]
Same issue with vscode on windows 10!

**Comment by brettmstevens7** [comment]
This was fixed in the last version. Thanks for bringing it to our attention!
