### ISSUE TITLE
Undisclosed advertising in the command panel?!

### ISSUE THREAD

**Issue by darkvertex** [swdotcom/swdc-vscode#6]
Dude, not cool:

![screenshot from 2019-02-05 11-46-57](https://user-images.githubusercontent.com/941331/52289471-1ba3b180-293c-11e9-9d3b-0f4f12995961.png)

Nowhere on [the extension page](https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode#overview), nor [the github repo's README](https://github.com/swdotcom/swdc-vscode/blob/45080255d857ad8cb18c24d83f1e3ad33ffc3f09/README.md), [nor your FAQ](https://www.software.com/faqs-categories/data-privacy), does it say you are doing advertising inside the extension. This is straight up *unacceptable.*

For the record, my problem is not the advertising. I understand servers cost money and this is promoted as a "free" service so I get that some form of advertising may be a revenue stream for you and that's fine within reason, but my issue is you did not disclose the advertising upfront. How am I supposed to trust you with time tracking my personal code if I can't trust you to disclose what your extension is doing? What next, are you sneak in UberEats promos as commented code blocks in my code??

If you wish to keep advertising but make it less _sketchy_, maybe mention some promo codes inside a changelog that appears on each update as you improve the extension? It'd be less of a breach of confidence that way. **At the very least** mention the in-panel advertising in your README.

I guess I'm gonna continue sticking with [Wakatime](https://wakatime.com/vs-code) until then. They never voided my trust by silently sneaking in any advertising in any of their extensions.

**Comment by andrewhli** [comment]
Hi there. I think you misunderstood our point with the food feature. It is not advertising. We are not affiliated with these services. We don't receive any compensation. We have never spoken with them. The feature is 100% for fun and convenience, to provide a bit of lighthearted fun during mealtimes. Feel free to let us know how we can make it look less like advertising.

**Comment by darkvertex** [comment]
I see! Thanks for clarifying and I'm genuinely glad it's not what I thought it was.

Perhaps not include the feature by default altogether? (Maybe hide it as an obscure easter egg?) To me it feels really out of place as it seems not really aligned with the primary purpose of this extension which is to track coding time.

I have now checked the code deeper and [indeed you don't even have identifiable promo codes so I 100% believe you](https://github.com/swdotcom/swdc-vscode/blob/4816759c5822b3b6d44b6f6a065d642c51093442/lib/MenuManager.ts#L85) right now, but I probably won't be the only one to feel a little confused by this "feature" and wrongly interpret it as a violation of trust when it's in fact just a little "joke".

I would strongly suggest to either hide it as an easter egg or simply remove it. Thanks again for promptly replying to this.

(ps: Now I really want some tacos, dammit..)

**Comment by andrewhli** [comment]
Thanks for understanding! We're working on making your ideas happen today.

**Comment by andrewhli** [comment]
We've pushed Code Time v0.5.60, so that it no longer shows the tacos or order options in the status bar. Let us know if you have more ideas around easter eggs or other coding-related features in the plugin.

**Comment by darkvertex** [comment]
Thanks Andrew. :+1:
