### ISSUE TITLE
When the view is split, the editor doubles the time

### ISSUE THREAD

**Issue by piotrsynowiec** [swdotcom/swdc-vscode#63]
**Describe the bug**
I noticed that although I've spent 7 minutes in Harvest on coding, because I have split the editor, the timer is adding extra time.

**Steps to reproduce**
1. Just split the editor, so you have two views. The timer will start counting time faster.

**Expected behavior**
It should count the time normally.

**Desktop (please complete the following information):**
macOS 10.15.2 Beta (19C46a)
Code Time v1.3.0

**Comment by brettmstevens7** [comment]
Thanks, we'll look into this.

**Comment by mmclead** [comment]
This is definitely fixed now.   Going to close.  But, please reopen if this is still an issue for you.
