### ISSUE TITLE
Make VS Code Extension available to Azure Data Studio

### ISSUE THREAD

**Issue by pocki** [swdotcom/swdc-vscode#64]
Can you please make the Extension for Visual Studio Code also available to [Azure Data Studio](https://github.com/microsoft/azuredatastudio). 

Azure Data Studio has the same base as Visual Studio Code and I can install the extension manually with "Install from VSIX..." successfully. It looks like it is also working correctly.

**Comment by brettmstevens7** [comment]
Thanks for the suggestion! We'll do some more investigation to see what it would take to fully support this.

**Comment by bjacobson26** [comment]
added to backlog
