### ISSUE TITLE
Wrong time metrics

### ISSUE THREAD

**Issue by simeon4real** [swdotcom/swdc-vscode#65]
My total code time for days and weeks is incorrect. coded for 7 hours yesterday and only reported 0.1 hours on the extension dashboard and the web app

**Comment by brettmstevens7** [comment]
@simeon4real could you include a screenshot of what you see vs. what you expect to help us debug?

**Comment by faldor20** [comment]
I am having a similar issue:
![image](https://user-images.githubusercontent.com/26968035/73844639-af200300-486c-11ea-815d-a37dc8245671.png)
As you can see my weekly breakdown does add up to my last two days of work.
