### ISSUE TITLE
How do you sign up?

### ISSUE THREAD

**Issue by RobFosterNYC** [swdotcom/swdc-vscode#66]
It only wants me to sign in, but how can I sign in if I dont have an account to sign into ?
im a bit confused by this.
Ive been coding all day for more than 9 hours and this plugin is showing that I only did 7 lines of code and only coded for 20 minutes ?.......LOL
Ive been practicing most of the day, so im a bit confused....lol
Does it need me to log in to get the metrics, or is this broken ?

**Comment by brettmstevens7** [comment]
Hi Rob, sorry for any confusion. "Log in" will work just like "Sign up". You should only have to log in via the plugin once and see /onboarding?token=xxx in the URL. With regards to your data not showing up, can you share more details to help us reproduce the bug?

**Comment by RobFosterNYC** [comment]
There is not much I can say in regards to this.
All I did was code all day and when I clicked on the 'code time today"  button on the lower right corner
of VS-Code, thats when a window pops up and gives me all the metrics that says I didnt code.
Thats pretty much what steps happened.

**Comment by RobFosterNYC** [comment]
A few feedback points I would like to share.
1. - please place an actual (Sign-Up) and my friends I referred and I all got confused as to how to sign up.
when you have a bunch of people in discord all confused about the same thing, there is a problem. :)
2. - Would love to have an actual graphical version option to view within VS-Code,
would be nice to have that option.
3. - Does this also work for Visual Studio 2019 ?
would be nice if it did :)  since its by the same company aka microsoft.

Anyways, I reinstalled the plugin and tried again and now I am signed in.
even though that Log In is extremely confusing.  :)

Thanks.

**Comment by brettmstevens7** [comment]
Thanks for the feedback @RobFosterNYC. We fixed the issue with losing your data going forward. Appreciate you pointing that out. I'll share your other feedback about the login button with the team.

We do have a Code Time extension for Visual Studio here: https://github.com/swdotcom/swdc-visualstudio.
