### ISSUE TITLE
Time not keeping or updating or registering

### ISSUE THREAD

**Issue by 1sdc0d3r** [swdotcom/swdc-vscode#67]
**Describe the bug**
It is not keeping track of my time at all. I was programming from 9 am Dec11, to 1 am Dec12. It says I coded 1.4 hours. This is not ok with me. I code every day for hours on end just like today day after day and I need this to be accurate. Yesterday It has me logged at 0 coding time at all. And last week ONLY ~23hrs. That is a ridiculously low amount for me. Please fix this ASAP. It's not even tracking simple time.... I need this, please.

**Steps to reproduce**
1. Go to 'VSCode'
2. Click on 'CodeTime in bottom status bar'
3. Click on  'Code Time Dashboard'

**Expected behavior**
To see how many hours I coded today and yesterday. And other data located there.

**Screenshots**
<img width="926" alt="Screen Shot 2019-12-12 at 12 50 49 AM" src="https://user-images.githubusercontent.com/54449993/70692879-89fe8200-1c79-11ea-9ec6-1ee9da73ace8.png">
<img width="672" alt="Screen Shot 2019-12-12 at 12 50 28 AM" src="https://user-images.githubusercontent.com/54449993/70692881-89fe8200-1c79-11ea-89a3-7d6ded4cd4eb.png">
**Desktop (please complete the following information):**
 - OS: [e.g. macOS Mojave 10.14.6]
 - Plugin version [e.g. Code Time v1.2.1] - unsure (latest update)

**Additional context**
Please email me at fish0859@gmail.com. I submitted the issue before that was "closed", and that was because I was misunderstood. Please contact me if you have any questions at all and please get this fixed ASAP!!!

**Comment by brettmstevens7** [comment]
Hi Braden,

Thanks for bringing this to our attention!

We uncovered an issue with how we were caching the dashboard locally. We've added new check to see if you've passed into a new day, in which case we will invalidate your local cache and fetch a new dashboard with yesterday's updated results. You should see data for "Yesterday" in your dashboard now. If you code past midnight in the future, you should also see an accurate number for "Yesterday."

With regards to the 23 hours last week - how much lower does that number seem to you than what it should be?

**Comment by 1sdc0d3r** [comment]
So Sorry for the late response. 23 hrs is very low, I spend my days coding from 9am to about 3am. Repeat this Monday through Friday and sometimes weekends as well. This is a very low number for me.

**Comment by bjacobson26** [comment]
This issue should be resolved. Please re-open if you are experiencing the same problem with CodeTime v2.3.2 or greater. Thank you!
