### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Paurian** [swdotcom/swdc-vscode#68]
- Issue Type: `Bug`
- Extension Name: `swdc-vscode`
- Extension Version: `1.1.30`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.38.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 459,
		"activateCallTime": 0,
		"activateResolvedTime": 27,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```

**Comment by bjacobson26** [comment]
closing this issue for now. If this issue persists in CodeTime v2.3.2 or greater, please re-open! Thank you!
