### ISSUE TITLE
Switch to another account

### ISSUE THREAD

**Issue by mrghasemi1992** [swdotcom/swdc-vscode#69]
**Bug:**
I removed VSCode totally from my Mac and install it again + it's extensions like Code Time. But after installing, this extension logs me in to the previous account that I don't want it. How to switch to the new account?

**System Info:**
 - OS: MacOS Catalina
 - Plugin version 1.3.9

**Comment by Narshe1412** [comment]
I'm also interested on this

**Comment by RubenVinke** [comment]
I'm having the same problem, there doesn't seem to be a logout option.

**Comment by brettmstevens7** [comment]
We're working on a feature to allow you to switch web accounts using a token -- stay tuned.

**Comment by brettmstevens7** [comment]
Following up on this thread. We now have a "Switch Account" feature for VS Code.
<img width="374" alt="switch_account" src="https://user-images.githubusercontent.com/27828739/91675800-886c3700-eaf2-11ea-9e1e-539b175facda.png">
