### ISSUE TITLE
Code Time Metrics opening on it's own

### ISSUE THREAD

**Issue by LeedanJohnson** [swdotcom/swdc-vscode#7]
If I open the metrics page once, it will then open itself and take focus roughly every minute. This is incredibly annoying as it interrupts, well, everything.

**VSCode version info**
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

**Code Time version**
v0.5.61

**Comment by brettmstevens7** [comment]
Hi Leedan, thank you - we just pushed a fix for this issue in v0.5.63. I'll mark this as closed, but let me know if problem still persists after you update.

**Comment by andrewhli** [comment]
Hi @LeedanJohnson  - we're live on Product Hunt! Would appreciate any support you can give: https://www.producthunt.com/posts/code-time
