### ISSUE TITLE
Heatmap not showing any data

### ISSUE THREAD

**Issue by RaviPabari** [swdotcom/swdc-vscode#70]
![Capture2](https://user-images.githubusercontent.com/46424422/71918298-049ebc80-31a8-11ea-8e38-d7e9472d48f8.PNG)
![Capture](https://user-images.githubusercontent.com/46424422/71918324-11bbab80-31a8-11ea-9055-0e922380bfc7.PNG)
 I coded for 2.5hr on sunday and around 6-9 and the heatmap shows time period 12-1 and does not show any data about current day

**Comment by brettmstevens7** [comment]
Hi @RaviPabari, thanks for submitting this bug. The heatmap you see is for last week (Sun Dec 29 - Sat Jan 4). You will see the 2.5 hr from this Sunday (Dec 5) at the end of this calendar week.

**Comment by RaviPabari** [comment]
> Hi @RaviPabari, thanks for submitting this bug. The heatmap you see is for last week (Sun Dec 29 - Sat Jan 4). You will see the 2.5 hr from this Sunday (Dec 5) at the end of this calendar week.

Okk thanks for the info and the extension is dammm♥
