### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by VegasC** [swdotcom/swdc-vscode#71]
**Describe the bug**
app.software.com’s server IP address could not be found.

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Go to vs code '...'
2. Click on code time '....'
3. on the pop-up menu click on web dashboard '....'

**Expected behaviour**
As usual, I was expecting to see my code time displayed on the web dashboard.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Linux
 - Plugin version [e.g. Code Time v1.3.9]

**Comment by Bkbrawler04** [comment]
@VegasC are you still experiencing issues?

**Comment by Bkbrawler04** [comment]
This issue has been opened for 21 days without a response. Closing.
