### ISSUE TITLE
Logged Time resetted to 0

### ISSUE THREAD

**Issue by pocki** [swdotcom/swdc-vscode#76]
**Describe the bug**
Every few minutes the time gets resetted to 0. It seems to be the same as #60 

**Steps to reproduce**
1. Code some hours in Visual Studio
2. View every few minutes to the status bar and see a low value (near 0) and lower as some minutes ago

**Expected behavior**
Counting up the whole day during coding

**Desktop:**
 - OS: Windows Server 2016
 - Plugin version Code Time v0.1.70 in Visual Studio 2019 (v16.4.4) and Code Time v2.0.6 in Visual Studio Code (v1.41.1)

**Additional context**
Only one Visual Studio or Visual Studio Code is open at the same time
I updated to the latest versions of Code Time today on both Visual Studio and Visual Studio Code, two weeks ago it worked as expected (last week i did not use Visual Studio or Code)

**Comment by guy-mev** [comment]
Can confirm with MBP 10.14.6
VS Code 1.39.1
Code Time 2.0.6

**Comment by brettmstevens7** [comment]
@pocki @guy-mev we had a couple things going on here that were just fixed. No need to install a new version; it was with an API. Let us know if you still encounter any issues. Thank you!!

**Comment by pocki** [comment]
Thanks, looks great and it's working again.
