### ISSUE TITLE
"Code time: 0 min" all the time and ~/.software/CodeTime file has weird permissions

### ISSUE THREAD

**Issue by darkvertex** [swdotcom/swdc-vscode#8]
Hello,

I wanted to wait a few days in case it was some kind of delayed daily process thing, but it's been 3 days or so that after I logged in, presumably everything is working but I see `Code time: 0 min` all the time on the bottom right of VSCode and the web dashboard (and the "Code time report" from vscode) reports no data at all. (It's showing the default charts explaining what data may look like.)

Is there some secret debug log I could paste to help you investigate this?

I also noticed that the internal file `~/.software/CodeTime` had been created by my user but with some bizarre permissions not allowing me to edit the file, which I guess did not help.

It was like this: (notice I have no user read rights on the file, wtf?)
```bash
> ls -l ~/.software/
total 72
drwxrwxr-x   2 alan artists   1536 Feb  8 11:37 ./
drwxr-xr-x 192 alan games   207872 Feb  8 11:36 ../
--wxrw--wt   1 alan artists   2833 Feb  8 11:35 CodeTime*
-rw-rw-r--   1 alan artists    227 Feb  7 14:59 session.json
```
After seeing that, I opened the permissions to my user:
```bash
> ls -l ~/.software/
total 72
drwxrwxr-x   2 alan artists   1536 Feb  8 11:37 ./
drwxr-xr-x 192 alan games   207360 Feb  8 11:37 ../
-rw-rw-r--   1 alan artists   2833 Feb  8 11:35 CodeTime
-rw-rw-r--   1 alan artists    227 Feb  7 14:59 session.json
```
...but it still wasn't working. Restarted VSCode, reinstalled the extension, restarted vscode again for good measure and the permissions went back to being un-readable by my user.

I think there's a bug somewhere?

Here's my vscode info if it helps:
```
Version: 1.31.0
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-06T08:51:24.856Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 3.10.0-693.21.1.el7.x86_64
```

**Comment by andrewhli** [comment]
Hi Alan. This is a known issue that was introduced yesterday. We're working on it today and will let you know when it's done.

**Comment by darkvertex** [comment]
Ah, cool. I can wait. Thanks for quick response.

Let me know when I should update.

**Comment by darkvertex** [comment]
Looks like a recent update solved this issue, though it seems I did have to open the file permissions one last time.

Now I see "Code time: 17m". It's a start.

**Comment by andrewhli** [comment]
Hi Alan - Wanted to check in on this issue. Did you experience any other difficulties recently with Code Time?

**Comment by darkvertex** [comment]
Nope, it appears to be working so far. The plugin is reporting stats fine as far as I can tell.

I hope you guys improve the web dashboard. I feel it's all in one long page which is cool in its own right, yet without many options to filter by project or time period. I imagine that'll come with time, but just mentioning it. :)

**Comment by andrewhli** [comment]
Hi Alan - we're live on Product Hunt! Would appreciate any support you can give: https://www.producthunt.com/posts/code-time

**Comment by darkvertex** [comment]
Upvoted. :+1:

![have an upvote!](https://media.giphy.com/media/Q29bhBY4Jbuta/giphy.gif)

**Comment by andrewhli** [comment]
Appreciate the support! We'll be working on the music integration next

**Comment by darkvertex** [comment]
Great! I'm super curious to find out which music genres or bands make me the most productive. hehe
