### ISSUE TITLE
Pause KPM after a delay

### ISSUE THREAD

**Issue by DAmNRelentless** [swdotcom/swdc-vscode#80]
##### SUMMARY
The keystrokes per minute detection should pause after a specific time of inactivity.
I often read through articles and forums while I am coding. Maybe you also want to make yourself a coffee while Visual Studio Code is still open. I think the kpm count should be paused after like one minute inactivity so it won't affect your "score".

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION
The feature would be used automatically. If an inactivity of like one minute is detected, it should pause the recording of the keystrokes per minute.
It would help to show an actual kpm value and not show false values because you weren't active for 10 minutes.

**Comment by bjacobson26** [comment]
Thank you for the suggestion. Our current timeout is 15 minutes. We are considering adding a feature to allow the user to configure this. This has been added to our backlog. 👍
