### ISSUE TITLE
Cannot login from multiple PCs

### ISSUE THREAD

**Issue by Riccorl** [swdotcom/swdc-vscode#82]
I cannot login from multiple PCs with the same email. Whenever I try to login from VS Code, it opens the signup page and then i get this error "Sorry, a user already exists with that email."

**Comment by brettmstevens7** [comment]
Sorry for the bug @Riccorl. On our priority list.

**Comment by Hans5958** [comment]
Same here! I thought "multiple vscode, one account" wasn't a feature on this extension.

**Comment by danst3in** [comment]
@Hans5958 Where is that file located, and how do you sign back in if you got signed out on your original machine?

**Comment by bjacobson26** [comment]
Hi everyone. You should be able to log in to your account on multiple machines. Once you have installed CodeTime, click on one of the options to log into your account:

![image](https://user-images.githubusercontent.com/9271952/91751749-29ea9b80-eb7a-11ea-9523-340fb070e083.png)
