### ISSUE TITLE
Share to slack

### ISSUE THREAD

**Issue by usamamoinakhter** [swdotcom/swdc-vscode#84]
##### SUMMARY

```paste below
Is there an option to automatically share the progress on a specific slack channel?
```

##### ISSUE TYPE
- Feature Request

**Comment by andrewhli** [comment]
Hi @usamamoinakhter - This is a good idea, and our team has built the functionality to support it. We are curious about which metrics you'd like to share the most, and how you'd like the Slack message to look. 

Do you want us to share a couple specific metrics in a short inline Slack message? Or would you like the seed message to look like the following dashboard, allowing you to cut what you choose to cut? Or are you thinking of another format?

![Uploading Screen Shot 2020-04-01 at 8.25.53 PM.png…]()

**Comment by andrewhli** [comment]
@usamamoinakhter - We'd also like to invite you to our user community, where you can discuss product ideas directly with our team and get access to early features: https://join.slack.com/t/software-community/shared_invite/zt-bz6xhfys-xtlAa8TGK0plx0J8JSYy7A

**Comment by usamamoinakhter** [comment]
If the user can select what should be shared and what not that would be great I think

**Comment by bjacobson26** [comment]
added to backlog
