### ISSUE TITLE
Mixed numerical basis

### ISSUE THREAD

**Issue by robsonsobral** [swdotcom/swdc-vscode#89]
(Is "numerical basis" the right term?)

**Describe the bug**

The summary of   **📂 Weekly top projects** mixes minutes and decimals.

```paste below
 19.8 hrs
 19.0 hrs
  2.4 hrs
  1.2 hrs
   58 min
    1 min
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Work a really short time on a project
2. Check your summary next week
3. Scroll down to **📂 Weekly top projects**

**Expected behavior**
The data should be shown all on the same basis.
```paste below
"58 min" as "0.96 hrs"
```

**ACTUAL RESULTS**

```paste below
  1.2 hrs
   58 min
```

**Screenshots**

**Desktop (please complete the following information):**
 - Win10
 - Code Time v2.2.6

Thank you so much!

**Comment by bjacobson26** [comment]
thank you for the suggestion. Since some user's may prefer the current behavior, we will consider this a feature request for the ability to configure the "numerical basis" to hours or minutes. Added to our backlog! Thanks again 👍
