### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ClintonVasco2020** [swdotcom/swdc-vscode#92]
- Issue Type: `Bug`
- Extension Name: `swdc-vscode`
- Extension Version: `2.2.7`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Bkbrawler04** [comment]
Hi @ClintonVasco2020 ,
Can you please paste the contents of the output here? If it's too large to paste, please use https://gist.github.com/. Thank you.
