### ISSUE TITLE
Requesting ability to track hours by git branch name

### ISSUE THREAD

**Issue by castastrophe** [swdotcom/swdc-vscode#96]
##### SUMMARY

I would love the ability to track hours by git branch name.  This is helpful for reporting project actuals into a management system (such as Rally or Jira).

##### ISSUE TYPE
- Feature Request

##### ADDITIONAL INFORMATION

Being able to capture hours spent actively coding in the editor by branch names provides me with fully accurate "actuals" to port in to our project management systems (Rally, Jira, etc.).  Actuals are notorious guesswork and I would like to have better insight into how much time is actually spent on each project.

An example mock-up for how this report could be visualized:

<img width="375" alt="Screen Shot 2020-06-08 at 9 40 40 AM" src="https://user-images.githubusercontent.com/1840295/84037148-2b863800-a96c-11ea-9a8b-c6a4ad66e8d4.png">

**Comment by mmclead** [comment]
Thanks for the mockup!  I like the look.    We are working on more features just like those for an upcoming release.

**Comment by castastrophe** [comment]
I’m a front-end dev so feel free to reach out if you need anything. 😄

**Comment by bjacobson26** [comment]
added to backlog
